### ISSUE TITLE
Non 'static messages

### ISSUE THREAD

**Issue by axos88** [actix/actix#104]
It seems like the requirement for M: 'static was relaxed here: https://github.com/actix/actix/commit/17ef4716e301dd45de58dfbf551e1af00dffdc60, however it seems like https://github.com/actix/actix/blob/ad7442905c17585d0047e3f3d1cf2ec79ae4353e/src/address/envelope.rs#L31 still requires it to be static.

Is it something that was forgotten, or have I misunderstood that commit?

I'm trying to send a message 

```
pub struct Write<'a T, PATH: Iterator<Item = &'a str>> where T: Serialize + Send { pub path: PATH, pub value: T }

impl<'a, T, PATH: 'a> Message for input::Write<'a, T, PATH> where T: Serialize + Send, PATH: Iterator<Item = &'a str> {
    type Result = Result<(), Error>;


impl<'a, T: 'static, PATH: 'a> Handler<input::Write<'a, T, PATH>> for Actor where T: Serialize + Send, PATH: Iterator<Item = &'a str> {
    type Result = Result<(), Error>;

    fn handle(&mut self, msg: input::Write<'a, T, PATH>, ctx: &mut Self::Context) -> Self::Result {
       unimplemented!()
    }
}

....

addr.send(msg).and_then { |res| unimplemented!() }

```

**Comment by fafhrd91** [comment]
it is not possible to remove static lifetime

**Comment by axos88** [comment]
So what's the point of https://github.com/actix/actix/commit/17ef4716e301dd45de58dfbf551e1af00dffdc60 then, if it's still not possible to send around non-static messages?
