### ISSUE TITLE
Actix v0.6 can't find Addr's try_send(msg) method. Is removed?

### ISSUE THREAD

**Issue by kingxsp** [actix/actix#105]
Actix v0.6 can't find Addr's try_send(msg) method. Is removed?  Why? This is a very useful method. Can you go back? Or do_send(msg) return SendError info.

**Comment by axos88** [comment]
It was removed in https://github.com/actix/actix/commit/17ef4716e301dd45de58dfbf551e1af00dffdc60#diff-b18cf37ebefb4a196f97752ee1f1ac27

I think `do_send` will always send the message, even if the queue is full. However `send` will return an error immediatly as far as I see: `https://github.com/actix/actix/blob/17ef4716e301dd45de58dfbf551e1af00dffdc60/src/address/channel.rs#L220-L222`.

**Comment by axos88** [comment]
do_send will disregard the mailbox being full, and will force the message onto the queue.

**Comment by fafhrd91** [comment]
try_send is restored
