### ISSUE TITLE
Handling panics in Actors run by SyncArbiters

### ISSUE THREAD

**Issue by Xorlev** [actix/actix#110]
Hi there!

First off, I've been a huge fan of Actix (and Actix Web) so far. Thank you for all of your hard work! :)

Like the issue title says, I'm curious about how to _correctly_ handle panics of Actors running in separate threads.

For some context, I'm writing an IRC relay bot using the irc crate and actix. I have an actor wrapping the future::Stream of events coming from the IRC client. So far so good. The IRC client is running on the main thread sending these events to another actor running on a different thread (via a SyncArbiter):

```rust
let sys = actix::System::new("ircrelay");
let message_handler = Arbiter::start(|_| MessageHandler::with_scrollback_capacity(100));

let message_handler_clone = message_handler.clone();
let cfg_clone = config.clone();
let _irc_actor: Addr<Unsync, IrcActor> =
        actix::Supervisor::start(move |_| IrcActor::new(message_handler_clone, &cfg_clone));
```

From my IrcActor, I send the message to the `MessageHandler`

```rust
if self.should_relay(&irc_message) {
    if let Some(message) = StructuredIrcMessage::from_message(irc_message) {
        self.handler_addr.try_send(message).expect("Whoops, failed to send!");
    }
}
```

At one point I had a panic occur in the recipient as a result of the message, which meant the thread died. It keeps running along despite the panic until another message comes through at which point:

```
thread 'main' panicked at 'Failed to send!: SendError::Closed(..)', libcore/result.rs:945:5
```

Which is expected, but untimely. In terms of wanting to write reliable software, I'd ideally like to recover from that failure as quickly as possible (possibly by killing the process and letting systemd restart the process) rather than having a ticking timebomb waiting for the next message to cause the main thread panic. I'd originally used `do_send` and the process silently failed until I noticed it was failing.

I could wrap my handler bodies in [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) but that doesn't really appeal to me and if anything that should happen at the framework level as a way of cleanly aborting the process.

What's the right way of dealing with panics in actors in other threads?

**Comment by fafhrd91** [comment]
i am not sure how to handle panics in this case, we may start sync actor in catch_unwind.

if you want to restart process immediately you can use "panic=abort" in your cargo.toml

```
[profile.release]
panic = "abort"
```

**Comment by DoumanAsh** [comment]
Well, to be honest, in first place panic is pretty abnormal condition and I would consider it actually a bug for your code.

So why wouldn't you prevent panic in first place?

**Comment by DoumanAsh** [comment]
Considering that panic implies abnormal state, I believe it would best to adapt approach similar to `Supervisor`.
I.e. So if actor is stopped(especially abnormally) there should be also way for user to clean-up state in one place so we should rely here on [Supervised](https://actix.rs/actix/actix/trait.Supervised.html) to provide state clean-up

**Comment by fafhrd91** [comment]
I don't it is possible in general case. we would need to add `UnwindSafe` constraint, which is problematic especially for async code. it is easier to restart whole thread.

**Comment by Xorlev** [comment]
There's some state that's hard to clean up from a position of something like `Supervised`, i.e. a poisoned mutex (if you're lucky -- I can imagine other more subtle issues that could occur). I'm not sure restarting the thread would always be the right thing to do.

**Comment by fafhrd91** [comment]
Ok, lets add optional exit on panic for sync arbiter.
