### ISSUE TITLE
send failed because receiver is full

### ISSUE THREAD

**Issue by marioidival** [actix/actix#121]
I got this error `send failed because receiver is full`

```rust
extern crate actix;

use actix::prelude::*;

struct Count(i64);

impl Message for Count {
    type Result = i64;
}

struct Counter {
    counter: i64,
}

impl Actor for Counter {
    type Context = Context<Self>;
}

impl Handler<Count> for Counter {
    type Result = i64;

    fn handle(&mut self, msg: Count, _ctx: &mut Context<Self>) -> Self::Result {
        println!("current counter {}", self.counter);
        self.counter += msg.0;
        self.counter
    }
}

fn main() {
    System::run(|| {
        let addr = Arbiter::start(|ctx: &mut Context<_>| {
            ctx.set_mailbox_capacity(0);

            Counter { counter: 1 }
        });

        for _ in 1..100 {
            match addr.try_send(Count(1)) {
                Ok(_) => (),
                Err(e) => eprintln!("error: {}", e),
            }
        }
    });
}
```

**Comment by DoumanAsh** [comment]
Please check out documentatino on [try_send](https://actix.rs/actix/actix/struct.Addr.html#method.try_send) 

>This method fails if actor's mailbox is full or closed. This method register current task in receivers queue.

You should use [send](https://actix.rs/actix/actix/struct.Addr.html#method.send) instead for such case when you want to spam your mailbox

Or you should adjust your mailbox capacity https://actix.rs/actix/actix/struct.Context.html#method.set_mailbox_capacity

**Comment by fafhrd91** [comment]
this example is right. problem is a concurrency. `Arbiter::start()` creates new thread and starts
actor in this thread, but you get `Addr<A>` before actor get started. so initially
when you do `add.try_send()` you send messages to default sized mailbox (16 elements)

if you insert some delay before `for` loop, you'll get right behavior 
i.e insert this code before `for` loop: `thread::sleep(Duration::from_millis(100));`
