### ISSUE TITLE
Failure when compiling project

### ISSUE THREAD

**Issue by kjeremy** [actix/actix#125]
I'm seeing a new failure using Using rustc 1.29.0-nightly (e94df4acb 2018-07-31)

>      Checking actix v0.7.3
> error[E0433]: failed to resolve. Could not find `_core` in `failure`
>   --> C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.3\src\address\mod.rs:23:10
>    |
> 23 | #[derive(Fail)]
>    |          ^^^^ Could not find `_core` in `failure`
> 
> error[E0433]: failed to resolve. Could not find `_core` in `failure`
>    --> C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.3\src\actors\resolver.rs:133:10
>     |
> 133 | #[derive(Fail, Debug)]
>     |          ^^^^ Could not find `_core` in `failure`
> 
> error: aborting due to 2 previous errors

**Comment by fafhrd91** [comment]
it is fixed by actix-web master, I will release new version during this week

**Comment by fafhrd91** [comment]
as temp solution you can pin `failure_derive="=0.1.1"`
