### ISSUE TITLE
Macros or attributes to prevent repetition of impl ResponseType

### ISSUE THREAD

**Issue by superlou** [actix/actix#13]
I've noticed that I have a lot of repetition of `impl ResponseType<...` since a new one is required for each signal.  To DRY my code, I've defined the following macro:

```
macro_rules! response_type {
    ($Actor:ty, $Msg:ty, $item:ty, $err:ty) => (
        impl ResponseType<$Msg> for $Actor {
            type Item = $item;
            type Error = $err;
        }
    );

    ($Actor:ty, $Msg:ty, $item:ty) => (
        impl ResponseType<$Msg> for $Actor {
            type Item = $item;
            type Error = ();
        }
    );

    ($Actor:ty, $Msg:ty) => (
        impl ResponseType<$Msg> for $Actor {
            type Item = ();
            type Error = ();
        }
    );
}
```

This seems to work, though there may be a more elegant approach.  In a perfect world, it would be great to use an attribute as in the following example:

```
#[response_type(MyStatusEnum)]
impl Handler<PrivMsg> for Engine {
    fn handle(&mut self, msg: PrivMsg, ctx: &mut Context<Self>) -> Response<Self, PrivMsg> {
        println!("Source: {}, Target: {}, Text: {}", &msg.source, &msg.target, &msg.text);
        MyStatusEnum::Ok
    }
}
```

Is there a technique I missed that would make all of the above superfluous? Anyone else running into this repetition?

**Comment by fafhrd91** [comment]
1. `#[response_type(MyStatusEnum)]` is possible with proc_macro. but this works only on nightly.
also it shoulde be possible to destructure message and use message attributes as 
`handle` method parameters combined with impl Trait, it could be very nice

something like:
```rust
impl Engine {
    #[handler(PrivMsg)]
    fn do_thomething(&mut self, source: Source, target: Target, text: Text) -> Result<PrivMsgResponse> {
        println!("Source: {}, Target: {}, Text: {}", &msg.source, &msg.target, &msg.text);
        MyStatusEnum::Ok
    }
}
```

2. I've been thinking about `ResponseType`, I think it was wrong decision to use impl ResponseType on Actor, it is property of message itself. I changed master, message has to impl ResponseType.

**Comment by superlou** [comment]
On point 1, that seems to be a more typical pattern on frameworks I've seen in Rust, notably Rocket.  Callback-ish code is just a function, and the framework gets the information it needs from an attribute.

I think I agree with point 2.  Do you think that both 1 and 2 would be part of a 0.3, or is that more of a long-term thought?

**Comment by fafhrd91** [comment]
2 is for sure will be part of 0.3. 
I don't have time for 1, but if you'd like to work on it, I can move repo to organization and give write permission

**Comment by superlou** [comment]
I'll play around with 0.3 to see if that scratches my itch.  Not sure I'm qualified to take on proc_macro responsibly in my current state, so I wouldn't worry about moving to an organization.  However, if I have any success, I'll definitely contribute it back.

**Comment by fafhrd91** [comment]
0.3 is released

**Comment by superlou** [comment]
I updated my helper macros to:

```
macro_rules! response_type {
    ($Msg:ty, $item:ty, $err:ty) => (
        impl ResponseType for $Msg {
            type Item = $item;
            type Error = $err;
        }
    );

    ($Msg:ty, $item:ty) => (
        impl ResponseType for $Msg {
            type Item = $item;
            type Error = ();
        }
    );

    ($Msg:ty) => (
        impl ResponseType for $Msg {
            type Item = ();
            type Error = ();
        }
    );
}
```

This seems to work ok for 0.3 and lets me write the response quickly as follows:

```
response_type!(CreateBot);
pub struct CreateBot {
    pub engine: SyncAddress<Engine>,
    pub url: String,
    pub name: String,
    pub channels: Vec<String>
}
```

As I get more comfortable with the macro system, I'll look into a more Rusty solution.

**Comment by fafhrd91** [comment]
you may check "derive" proc macro, it is available in stable

**Comment by fafhrd91** [comment]
with derive macro, this could be something like:

for default case
```rust
#[derive(Message)]
pub struct CreateBot {
    pub engine: SyncAddress<Engine>,
    pub url: String,
    pub name: String,
    pub channels: Vec<String>
}
```

with custom response type

```rust
#[derive(Message)]
#[rtype(Item=Val, Error=io::Error)]
pub struct CreateBot {
    pub engine: SyncAddress<Engine>,
    pub url: String,
    pub name: String,
    pub channels: Vec<String>
}
```
this should work on stable

**Comment by callym** [comment]
I've done some rough work on this idea here: https://github.com/callym/actix/tree/feature/proc-macros

You can use `#[derive(Message)]`, `#[MessageResult(type)]`, `#[MessageError(type)]` and `#[derive(Actor)]`.
The code is functional but doesn't have a lot in the way of error handing or things like that.

```rust
#[derive(Message)]
#[MessageResult(usize)]
struct Sum(usize, usize);

#[derive(Actor)]
struct SumActor;
```

Which expands to:
```rust
impl ResponseType for Sum {
    type Item = usize;
    type Error = ();
}

impl Actor for SumActor {
    type Context = Context<Self>;
}
```

**Comment by fafhrd91** [comment]
you should be able to support both `Item` and `Error` in one attribute.

`#[Response(type)]` or `#[Response(type, error)]`

**Comment by fafhrd91** [comment]
btw do you want to move your code to actix organization

**Comment by callym** [comment]
> you should be able to support both `Item` and `Error` in one attribute.

I can add that if it's wanted, shouldn't be massively difficult 😄 

> btw do you want to move your code to actix organization

Yeah I'd be happy to do that! Is the best way to submit a PR?

**Comment by fafhrd91** [comment]
actix-derive implements all macros
