### ISSUE TITLE
Trait actix::io::WriteHandler should provide method to be called after each successful write

### ISSUE THREAD

**Issue by jchlapinski** [actix/actix#132]
Currently when actors use `FramedWrite` by implementing `actix::io::WriteHandler`, there is no way to know when data was actually successfully written. The trait only provides method called when there was an error in the underlying implementation. This makes it difficult to implement some stateful conversation without the need of some response from the other end.

In more detail: when sending data over TCP/IP we can be sure that the other end received the data, when the underlying stream was written and flushed without any I/O errors. We do not need to hear anything from the other end on the application level. 
Right now, since `actix::io::WriteHandler` does not have a method called when this happens, and `actix::io::FramedWrite::write(...)` does not return a future for the write operation, we cannot know when the data were actually send and received over the net.

There should be either a future returned from `actix::io::FramedWrite::write(...)` method or some method should be called on `actix::io::WriteHandler` trait after each successful write (and flush).

Please comment if I am missing something in this design, and perhaps it should be done differently. Thanks

**Comment by fakeshadow** [comment]
Use `<Actor as WriteHandler>::error` to intercept error generated by `AsyncWrite::{poll_write, poll_flush}`.
