### ISSUE TITLE
Expose TimerFunc in public API

### ISSUE THREAD

**Issue by jan-auer** [actix/actix#136]
Would it be possible to export `actix::utils::TimerFunc` to the public API just like `actix::utils::Condition`? 

I'm currently running into a case where I basically want to modify the future that is spawned by `AsyncContext::run_later` and thus would need access to it. Example code:

```rust
TimerFunc::new(duration, callback)
    // .map(), etc...
    .spawn(context);
```

My current workaround is this helper function (although I'd much prefer to use existing functionality from actix):

```rust
pub fn run_later<A, F>(
    timeout: Duration,
    f: F,
) -> impl ActorFuture<Item = (), Error = (), Actor = A>
where
    A: Actor,
    F: FnOnce(&mut A, &mut A::Context) + 'static,
{
    wrap_future(tokio_timer::Delay::new(Instant::now() + timeout)).then(|_, actor, context| {
        f(actor, context);
        fut::ok(())
    })
}

```

**Comment by DoumanAsh** [comment]
It is not much different from using `Delay` I'd say, but I don't see reason not to expose it.

Though we would need to document it properly at least.

**Comment by jan-auer** [comment]
It's obviously not a big deal not to have it, but would reduce the boilerplate necessary to schedule delays and avoid to explicitly pull in `tokio-timer` as a dependency. I'm happy to piece together a PR, if you like.

**Comment by DoumanAsh** [comment]
Yeah, I think it is ok to export it
