### ISSUE TITLE
Send over bounded channels

### ISSUE THREAD

**Issue by tekjar** [actix/actix#14]
Hi. Does it make sense to send messages over bounded channels and create blocking `send` and `send_timeout` in actor model? If so, is there a way to do it using this crate?

**Comment by fafhrd91** [comment]
I've been thinking about bounded channels, but I think it is more useful to have unbounded channels by default. but I am open for discussion or PR. Maybe it makes sense to make new `BoundedAddress`?

at the moment you can use bounded channel and pass receiver side to receiver actor, and use sender in source actor.
receiver would use `Context::add_stream` method and standard `Handler<M>` implementation.
sender can use `Context::wait()` to wait completion.

actix is still in early stages of development, would you like to participate?

**Comment by tekjar** [comment]
> actix is still in early stages of development, would you like to participate?

Yeah I'd love to contribute. I'll try to migrate [rumqtt](https://github.com/AtherEnergy/rumqtt/tree/async-await) to actix and see how it goes :)

**Comment by fafhrd91** [comment]
that would be awesome! I you hit any limitation just let me know, I am open to any changes in actix.

**Comment by tekjar** [comment]
@fafhrd91 Sure :)

**Comment by fafhrd91** [comment]
this is implemented

**Comment by cmnstmntmn** [comment]
@tekjar did you manage to run both rumqtt and actix ?
