### ISSUE TITLE
Clean up message buffer capacity rules

### ISSUE THREAD

**Issue by Firstyear** [actix/actix#141]
There are places in the code such as do_send/try_send that reference a messagebox limit. There seems to be no public method to alter the message limit, and a brief examination of the source code shows that the message limit is usize::MAX >> 1. As a result, it would probably be a good idea to either expose a function for altering message limit, or to discuss that the size is "very large" to avoid confusion.

**Comment by fafhrd91** [comment]
https://actix.rs/actix/actix/struct.Context.html#method.set_mailbox_capacity

**Comment by Firstyear** [comment]
I think that this should be reopened, as even with this documentation it took me nearly half an hour to work out what to do here, and that included having to look through examples and test code. I think that the documentation for set_mailbox_capacity needs to include examples, and that there should be an indication from the root actix::System documentation that each actor manages it's own mailbox queue size. Thanks,
