### ISSUE TITLE
Document thread pooling behaviour

### ISSUE THREAD

**Issue by Firstyear** [actix/actix#142]
Actors should allow multiple threads of execution to run at a time. It's unclear in actix if by default there is a single thread or multiple threads of execution. It would be great to have some examples and/or explanations of how actors interact with threads in actix/tokio to help consumers of the library understand the behaviours, and how to control the size of thread pools available.

**Comment by DoumanAsh** [comment]
I think unless specifically state, there is no threading in use.
Only `SyncArbiter` uses threads and it is stated in docs as it is the purpose of such Arbiter.

Though yeah I wouldn't mind to have more clarification

**Comment by mitchtbaum** [comment]
This is the best documentation I've found:
[Web Application Server by Rust with actix-web](https://qiita.com/atsuk/items/c04fffe4ed0e73a67cd0) by @atuk721 (ping)

**Comment by naturallymitchell** [comment]
See https://github.com/actix/actix/issues/19
