### ISSUE TITLE
Actix rebuilt on every build when used as a dependency

### ISSUE THREAD

**Issue by superlou** [actix/actix#15]
I'm pretty sure this is a result of https://github.com/budziq/rust-skeptic/issues/25.  It may be fixable by https://github.com/kvark/froggy/issues/26#issuecomment-310596443, though that seems like a bit of a hack.

**Comment by fafhrd91** [comment]
I am aware of this problem, I forgot to disable skeptic for release

**Comment by fafhrd91** [comment]
should be fixed. Could you test

**Comment by superlou** [comment]
Working, thanks!

**Comment by superlou** [comment]
This might actually be fixed in https://github.com/budziq/rust-skeptic/issues/25#event-1313412327 now.

**Comment by fafhrd91** [comment]
I still want to keep changer I made. to run tests with enabled skeptic you need to clean project, which is not good.
