### ISSUE TITLE
Broadcast to workers

### ISSUE THREAD

**Issue by prasannavl** [actix/actix#155]
Is there any way to broadcast a message to all the worker threads? Essentially I have a lot of data that's sufficient to just be eventually consistent in the state (which if I understand correctly is implemented  thread-locally). Now, I could do put them behind a pointer with synchronization mechanism (Arc<Mutex> or go the atomic route for primitives, etc), but since by nature it's sufficient for this state to be just eventually consistent, a much more efficient way would be to just broadcast a state to all workers, and let them update their own copy whenever they can process the message. 

Was wondering what's the best way to do this, in `actix` (and in actix_web, as a result).

**Comment by DoumanAsh** [comment]
It is a bit unclear what do you mean by worker thread?

If by worker you mean actor, then you could create [Recipient](https://actix.rs/actix/actix/struct.Recipient.html) which would be a generic way to send message of particular type.
With that you could put several of these recipients into array/vec and just iterate over it to broadcast messages.

For future questions please head over to our [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by prasannavl** [comment]
@DoumanAsh, will do about the gitter. Sorry, didn't realize it existed. 

And, by worker thread, I mean all the threads that actually hold a copy of the state, in the context of which messages get executed. I don't fully understand the workings of the Recipient. Will have a look at that and head over to gitter if it does indeed solve the issue.

**Comment by DoumanAsh** [comment]
if you're talking about actix-web then the story would be different.
You could create Actor that would manage state(most likely database) and address it when you need to access state.
Anyway the questions like that is better discussed at gitter
