### ISSUE TITLE
Broken example for actix::fut::ActorFuture

### ISSUE THREAD

**Issue by akurdyukov** [actix/actix#156]
I'm trying to implelement an actor forwarding responses just like an example in https://docs.rs/actix/0.7.5/actix/fut/trait.ActorFuture.html

But it does not work, because `returned_future` is not defined. Finishing with `Box::new(update_self)` does not help either because type mismatch - `ResponseActFuture` forces message type `Result<Item, Error>`. But `addr.send()` return future of `Item`.

Maybe there's some example I can fix docs with?

**Comment by DoumanAsh** [comment]
Yeah sorry about it, since example is `no_run` it is not being compiled.

I'm not sure why `update_self` wouldn't work though without looking at example of error.
Because from code itself it looks like it you should get `Item=(), Error=Error`

**Comment by NPN** [comment]
Looks like this was fixed in cbc0dfebc38ced2f3706c7b3a119de72c473650c, unless there's still some problem with using `update_self`.
