### ISSUE TITLE
Support for Actors on different servers

### ISSUE THREAD

**Issue by cetra3** [actix/actix#16]
It would be nice to be able to have Actors running on completely different servers or different processes using something like [tarpc](https://github.com/google/tarpc) so you could delegate work out horizontally.

Use case would be that you have certain actors that are running on special hardware, such as GPUs etc..

**Comment by fafhrd91** [comment]
I agree, that would be nice. And I am a landing to add this functionality, I just don’t have enough time. But you are welcome to join.

**Comment by criloz** [comment]
capn-proto does this already and can be used in other languages  https://github.com/capnproto/capnp-rpc-rust.

**Comment by fafhrd91** [comment]
This is higher level problem, wire protocol is easy

**Comment by criloz** [comment]
@fafhrd91 what I refer is that the best approach and what I am using now, is to use both capn-proto and actix, capn-proto-rpc is written with futures, so is easy to integrate, also   capn-proto is no just  a wired protocol,  also a   binary format with encoder decoders in different languages, while tarpc only support rust, and most important capn proto play very good with actor design pattern, they both works  similary, you can desgin capabilities or object ( and send those capabilities to the other endpoint this allow the other endpoint use the capabilities methods, in short is very easy to implement the actor model with capnproto object, and finally capn-proto is a parse-free allocation free protocol. 

you can read more here https://capnproto.org/rpc.html

**Comment by fafhrd91** [comment]
@criloz Hmm, sounds interesting. I will definitely look into it more.

Btw It is not clear for me are you using capnproto with actix or you just suggest?

**Comment by criloz** [comment]
@fafhrd91  both, the difficult part could integrate both automatically using some sort of code generation, but it still will be easier that  create a new protocol, capnproto is already supported in c, c++, java, python, golang, etc.

I am using actix for asynchronically  model the local logic and state of my components, and expose some actors with capnp-roto to other components in the network

**Comment by fafhrd91** [comment]
this is pretty cool! would you mind share detail? I am very interested

**Comment by criloz** [comment]
@fafhrd91, sure. I am pretty happy with this library, I will prepare some small example within this week.

**Comment by fafhrd91** [comment]
@criloz example would be helpful! Thanks

**Comment by fafhrd91** [comment]
@criloz btw did you implement any kind of actor discovery protocol? and what is about address transparency?

**Comment by criloz** [comment]
@fafhrd91, I am using a combination of content addressing (distributed hash map) and  etcd cluster (raft), is what the app that I am working needs, I think that plain dns will be more than enough for most applications,  there are several microservices  (etcd-skydns, consul) that  do this very well, the idea is to  manage the capnproto connection  and when  a failure is detected  query the dns, and reconnect. for handle lost of the states in case of  actor failures,  I am investigating `viewstamped replication`,  but there is already some implementation raft in rust by the tikv team also worth to consider

**Comment by fafhrd91** [comment]
i am working on basic prototype 

https://github.com/actix/actix-remote

**Comment by fafhrd91** [comment]
@criloz would you like to join actix-remote development?

**Comment by criloz** [comment]
@fafhrd91 thanks for the invitation!!, unfortunately, I am very busy I can't take another responsibility at the moment :disappointed:

**Comment by fafhrd91** [comment]
sure, np

**Comment by vityafx** [comment]
I'd like to have an ability to have arbiter being a broker in message passing system and use one, like nanomsg/zeromq. So actors may be used on different PCs absolutely transparently to the code writer ("it just works") or in threads like now, without changing code. This would provide the framework with an ability to scale as how it wants and one more thing - the messages will be delivered with 100% chance because of broker.

**Comment by kellytk** [comment]
@vityafx I personally would like to try treescale/treescale as it's written in Rust and has an interesting architecture.

**Comment by jnicholls** [comment]
@kellytk Thanks for sharing treescale, looks interesting! Not sure its state of development, hasn't seen a commit in awhile.

**Comment by fafhrd91** [comment]
i am not planing to work on this problem.

**Comment by mitermayer** [comment]
@fafhrd91 has this been implemented / supported in some fashion since then ?
