### ISSUE TITLE
Stop system with error code

### ISSUE THREAD

**Issue by Michael-F-Bryan** [actix/actix#165]
Is there a way to stop the system with an error code? I know `System::current().stop_with_code(1)` exists, but the `stop_with_code()` function is `pub(crate)` and can't be accessed outside of `actix`.

I also tried sending a `StopArbiter(1)` to the system arbiter (`System::current().arbiter().do_send(StopArbiter(1))`) but that doesn't appear to do anything.

**Comment by DoumanAsh** [comment]
I think we should expose this method as public as there is currently no way to stop system with particular code

**Comment by fafhrd91** [comment]
i fine with making it public
