### ISSUE TITLE
Architecture Patterns

### ISSUE THREAD

**Issue by hybrisCole** [actix/actix#168]
Hi, so I sort of understand how to use this framework by now :), but I have little knowledge about the actor model, I would like to know if anyone could point me to a good architectural book to understand how can I best model my application based on the actix ideas. Maybe this is based on Akka and I could grab a good Akka book idk.

Thank you!

**Comment by jduan** [comment]
Erlang the is most popular actor-based language. A recent addition is the Elixir language which is a more modern language based on Erlang. Maybe you can find some architecture books on Erlang/Elixir.
