### ISSUE TITLE
Build error under Windows

### ISSUE THREAD

**Issue by callym** [actix/actix#17]
I'm getting errors when trying to build under Windows, all related to `src/actors/signal.rs`

```
unresolved import `tokio_signal::unix`
cannot find value `SIGHUP` in module `libc`
cannot find value `SIGTERM` in module `libc`
cannot find value `SIGQUIT` in module `libc`
cannot find value `SIGCHLD` in module `libc`
```

Should the use of unix-specific code be cfg-gated?

**Comment by fafhrd91** [comment]
try to build it with "cargo build --no-default-features"

I will disable all features by default in next release

**Comment by callym** [comment]
Thanks - that fixed it!

**Comment by fafhrd91** [comment]
fixed
