### ISSUE TITLE
Sync Arbiter docstring with the actual behaviour

### ISSUE THREAD

**Issue by anler** [actix/actix#173]
Hello, reading the doc string for the [Arbiter struct](https://github.com/actix/actix/blob/master/src/arbiter.rs#L29) I noticed it says:

> By default, a panic in an Arbiter does _not_ stop the rest of the System

but later, in the [`new_system`](https://github.com/actix/actix/blob/master/src/arbiter.rs#L140) function, which is called by the [`create_runtime`](https://github.com/actix/actix/blob/master/src/system.rs#L395) function, it explicitly sets `stop_system_on_panic`:

```rust
let fut = ctx.into_future(Arbiter {
    stop: None,
    stop_system_on_panic: true, // If the system Arbiter panics, stop the system.
});
```

Are they really not synced, or even with that flag set the behaviour is correct?

Thanks!

**Comment by DoumanAsh** [comment]
I think in either case it might be confusing, but accent should be made on `System`

**Comment by anler** [comment]
Ok, closing this issue then. Thanks!
