### ISSUE TITLE
thread '<unnamed>' panicked at 'no Task is currently running'

### ISSUE THREAD

**Issue by TatriX** [actix/actix#178]
Hi. We are encountering a panic during the execution of a migration script for an application running in production. 

It happens when we run a script which makes a lot of calls through the `actix-web` which triggers about 1000+ calls to a sync actor.

It works fine for the first like 100 requests, then panic happens and the rest of the calls are served almost immediately without actually doing anything.

```
thread '<unnamed>' panicked at 'no Task is currently running', /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:44:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at libstd/panicking.rs:411
   6: futures::task_impl::with
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:44
   7: futures::task_impl::current
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:115
   8: <actix::address::channel::AddressSender<A>>::park
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/channel.rs:372
   9: <actix::address::channel::AddressSender<A>>::try_send
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/channel.rs:276
  10: <actix::address::Addr<A>>::try_send
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/mod.rs:112

  /// application stack trace omitted

  15: <actix::sync::SyncContextEnvelope<A, M> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/sync.rs:337
  16: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/envelope.rs:67
  17: <actix::sync::SyncContext<A>>::run
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/sync.rs:237
  18: <actix::sync::SyncArbiter<A>>::start::{{closure}}
             at /home/tatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/sync.rs:115
```

**Comment by DoumanAsh** [comment]
Interesting, @fafhrd91 did you encounter such error in past?

**Comment by fafhrd91** [comment]
It is not possible to use tru_send from sync code

**Comment by tazjin** [comment]
> It is not possible to use tru_send from sync code

This is working fine (and has been in production for quite some time). It's only in this short burst situation that the error occurs.

Are you saying that it's generally unsupported (i.e. "don't do that"), but that it *might* work under certain circumstances?

**Comment by TatriX** [comment]
Ok, setting the runtime helped, thank you!

We have a `std::thread` which reads from the external queue and then `addr.send(..)` to the async actor, which in turn `try_send()` to the sync actor.

So when the sync actor's mailbox reaches it's capacity, actix tries to park the async's actor thread, and then panics. Thus adding a runtime fixes the issue.

Though it's a bit surprising and hard to debug, because the whole scheme works until specific criteria is met. It would be nice to somehow prevent this from happening, maybe by panicking without waiting for the first park, but of course I don't have enough insight to suggest the proper solution.

Thank you again!

**Comment by gnosek** [comment]
I'm hitting a similar issue (sending a bunch of messages from a `std::thread` to an actor panics when the target actor's mailbox is full).

(I think) I understand the problem but I don't understand the fix :/ What does "adding a runtime" mean here?

What I'm trying to achieve is basically:

```
thread::spawn(move || {
  // up to ~1M times:
  channel.try_send(...);
});
```

**Comment by fafhrd91** [comment]
@gnosek use .do_send

**Comment by gnosek** [comment]
This just panics later, when the recipient's mailbox is full. I need to send all the messages reliably, waiting for the recipient if I need to.

**Comment by TatriX** [comment]
@gnosek 
```rust
thread::spawn(move || {
    let _rt = tokio::runtime::Runtime::new().expect("Cannot create tokio runtime");
    // run your actors code here, while _rt is in scope
})
```

**Comment by gnosek** [comment]
@TatriX, I stumbled upon:

```
thread::spawn(move || System::run(move || {
  channel.try_send(...); // etc.
}
```

and now `try_send` works (though it still throws errors when the mailbox is full and I'm not yet sure how to block the sender instead of reporting errors). Is this equivalent?

(as you can probably see, I'm stumbling in the dark here)

**Comment by TatriX** [comment]
We are doing something like this:
```rust
if let Err(e) = recv.send(output).flatten().wait() {
```

**Comment by gnosek** [comment]
So now I'm getting a deadlock (only SIGKILL helps) whenever I call `wait()` from a thread. I think I've been there before and I switched to `do_send`, which clearly doesn't solve my problem. I'll see what happens when I use tokio::Runtime instead of System::run.

I can't really get a list of futures as I'm sending a stream of messages to the async actor (an actix websocket connection, to be precise). I probably could make this a `Stream` but I haven't wrapped my head around the API yet.

I'm basically trying to generate a ton of data in a `std::thread` and send it via a websocket connection.

**Comment by fafhrd91** [comment]
Try `System::new().block_on(channel.send())`

**Comment by gnosek** [comment]
No luck (I'm calling `System::new` from a separate thread):

```
thread 'arbiter:4fc128e2-dabb-4014-bf42-80ca10676b2e:actix-net-worker-0' panicked at 'Multiple executors at once: EnterError { reason: "attempted to run an executor while another executor is already running" }', libcore/result.rs:1009:5
```

**Comment by fafhrd91** [comment]
Seems you start system in thread with started system
