### ISSUE TITLE
Feature Request: Way to get a `WeakAddr<A>` or something which can later be converted to `Addr<A>`

### ISSUE THREAD

**Issue by feisuzhu** [actix/actix#187]
I'm writing a simple chat server and trying to represent every chat room as a corresponding `Actor`.
I need a mechanism to address these chat rooms (`fn query(key: K) -> Addr<A>`), which eventually will be something like `HashMap<K, Addr<A>>`.
But `Addr<A>` is a 'strong reference' to an `Actor`, so this registry prevents actors from dying.

Here's an example:
```rust
use std::collections::HashMap;
use std::mem::drop;

use actix::*;

#[derive(Debug)]
struct ChatRoom(u32);

impl Actor for ChatRoom {
    type Context = Context<ChatRoom>;

    fn started(&mut self, _ctx: &mut Self::Context) {
        println!("ChatRoom {} started", self.0);
    }

    fn stopped(&mut self, _ctx: &mut Self::Context) {
        println!("ChatRoom {} stopped", self.0);
    }
}

#[derive(Message)]
struct Msg(u32);

impl Handler<Msg> for ChatRoom {
    type Result = ();
    fn handle(&mut self, msg: Msg, _ctx: &mut Self::Context) {
        println!("ChatRooms receives {}", msg.0);
    }
}

struct User {
    rooms: Vec<Addr<ChatRoom>>,
    id: u32,
}

impl Actor for User {
    type Context = Context<User>;

    fn started(&mut self, _ctx: &mut Self::Context) {
        self.rooms.len(); // make rustc happy
        println!("Actor {} started", self.id);
    }

    fn stopped(&mut self, _ctx: &mut Self::Context) {
        println!("Actor {} stopped", self.id);
    }
}

fn main() {
    let sys = System::new("issue");
    let room1 = ChatRoom(1).start();
    let room2 = ChatRoom(2).start();

    let user1 = User {
        rooms: vec![room1.clone()],
        id: 1,
    }
    .start();
    let user2 = User {
        rooms: vec![room2.clone()],
        id: 2,
    }
    .start();

    // XXX: registry holds an `Addr<ChatRoom>` of ChatRoom(1)
    let mut registry: HashMap<u32, Addr<ChatRoom>> = HashMap::new();
    registry.insert(1, room1.clone());

    drop(room1);
    drop(room2);
    drop(user1);
    drop(user2);

    sys.run();
}
```
which gives output:
```
ChatRoom 1 started
ChatRoom 2 started
Actor 1 started
Actor 1 stopped
Actor 2 started
Actor 2 stopped
ChatRoom 2 stopped

```
`ChatRoom 1 stopped` is missing as expected.

I can't think of a way to accomplish this (let ChatRoom 1 die) without some serious cooperation between `ChatRoom` and `User` actors and `ChatRoom`'s registry(maybe another `Actor`).

What I propose is something like `std::rc::Weak` equivalent for `Addr<A>`.
If such thing exists the code above can be easily implemented as:
```rust
let mut registry: HashMap<u32, WeakAddr<ChatRoom>> = HashMap::new();
registry.insert(1, room1.clone().downgrade());
```

**Comment by DoumanAsh** [comment]
@fafhrd91 I need your opinion on this.
It should be possible to have weak address similar to RC pointers, but I'm somewhat 50/50 on this since weak pointers are in general very specialized thingies

**Comment by fafhrd91** [comment]
I don’t have opinion on weak, I am fine with adding support for weak addr

**Comment by hoodie** [comment]
follow up question here @fafhrd91, `WeakAddr` was in version `0.7.10`, but it was yanked.
I'd be interested in the feature, are you planning to release another `0.7.x` or should I wait for 0.8.0 instead?

**Comment by DoumanAsh** [comment]
We had to yank it since I removed `async` keyword and it broke actix-web.
Well I could possibly release one more `0.7` version
