### ISSUE TITLE
Example of running on multiple threads

### ISSUE THREAD

**Issue by kingoflolz** [actix/actix#19]
Hi fafhrd91,

Thanks for your work on actix, it is shaping up to be one of the most ergonomic and fleshed out actor libraries on Rust.

I'm working on an actor based routing algorithm simulator and would like to simulate large numbers of nodes, making use of multithreading to distribute the load across multiple threads.

I saw on the documentation that "Actors could run in multiple threads with support of Arbiter", and I was wondering if you could write a small example, showing how to spin up multiple arbiters on different cores, create new actors on different arbiters and how to send messages from an actor on one arbiter into an actor on another arbiter. 

Thanks in advance

**Comment by fafhrd91** [comment]
i'll add multiple threads example. 
you can check this example https://github.com/actix/actix-web/blob/master/examples/websocket-chat/src/main.rs#L194
code on this line starts arbiter (new thread) and runs ChatServer actor. back you get `SyncAddress` same as `Address` but with `Sync` boundary. then you can use this address to send messages to created actor. hope this helps. i'll add example later today

**Comment by fafhrd91** [comment]
@kingoflolz actix is still in early development stage, if you find any annoyinces or if you think of better api, pleas don’t hesitate and create ticket. And you are welcome to join

**Comment by kingoflolz** [comment]
I think I figured out how all the pieces fit together. Would be nice to see an example to see if I did it the _"right"_ way haha.

(My implementation is at https://github.com/kingoflolz/routing-actor)

**Comment by fafhrd91** [comment]
i checked your code, some notes

in world.rs line 123, you can just call you handler, something like:

```rust
 Handler::<Wake>::handle(self, Wake, ctx)
```

also instead on using Timeout directly, you can just use https://actix.github.io/actix/actix/trait.AsyncContext.html#method.notify or https://actix.github.io/actix/actix/trait.AsyncContext.html#method.run_later

**Comment by kingoflolz** [comment]
Thanks, didn't realize that Context also implements AsyncContext, which has a whole bunch of useful methods.

**Comment by fafhrd91** [comment]
closing. will include to user guide later

**Comment by naturallymitchell** [comment]
> closing. will include to user guide later

I found this issue while looking for it,
then found [actix – an actor framework for the Rust programming language](https://simplabs.com/blog/2018/06/11/actix.html),
which lead to this search query, `arbiter site:actix.rs/ -site:actix.rs/api -site:actix.rs/actix`,
which pulled up these recently written guides, [Arbiter - Actix](https://actix.rs/book/actix/sec-5-arbiter.html) and [SyncArbiter - Actix](https://actix.rs/book/actix/sec-6-sync-arbiter.html),
so I also made https://github.com/actix/actix-website/issues/82 to complete this issue.

**Comment by naturallymitchell** [comment]
Sewing with multiple spools of thread is like delegating work with delegates who deal the work items.  See #9
