### ISSUE TITLE
Src missing from docs.

### ISSUE THREAD

**Issue by DanielJoyce** [actix/actix#197]
Clicking on any src link in docs leads to page with missing source files

https://docs.rs/actix/0.7.9/src/actix/arbiter.rs.html#40-43

This link shows line numbers, but no source in the file. Its there for older releases but seems to break around 0.7.8 or so.

**Comment by DanielJoyce** [comment]
The source links do work for actix-web thought.

**Comment by DoumanAsh** [comment]
It is most likely rustdoc issue, as we don't really generate docs ourself

**Comment by DanielJoyce** [comment]
Then links to docs on actix.rs should link here 

https://actix.rs/actix/actix/

Instead of docs.rs
