### ISSUE TITLE
Actors access their own address

### ISSUE THREAD

**Issue by kingoflolz** [actix/actix#20]
Hi,

I'm wondering if there is any way that I have missed for accessing the actor's own address, as it would prevent ugly hacks like https://github.com/kingoflolz/routing-actor/blob/66890955029b4e16e8b7aedaa6eedb001f019321/src/node.rs#L39-L53

Thanks in advance

**Comment by kingoflolz** [comment]
Never mind, figured it out, should be using `ctx.address_cell().unsync_address();`

**Comment by fafhrd91** [comment]
address_cell is for internal use. You should use https://actix.github.io/actix/actix/prelude/trait.AsyncContext.html#method.address
