### ISSUE TITLE
error: expected identifier, found reserved keyword `async`

### ISSUE THREAD

**Issue by atuk721** [actix/actix#200]
The following error is occurred when an `async` method is used using rust 2018 edition.

```
error: expected identifier, found reserved keyword `async`
   --> src/main.rs:110:19
    |
110 |         Response::async(task)
    |                   ^^^^^ expected identifier, found reserved keyword
```

I think it is the same problem to [this](https://github.com/actix/actix-web/issues/613) and the method name is needed to change.

**Comment by DoumanAsh** [comment]
Oh there was more? Well I'll rename it later on

**Comment by DoumanAsh** [comment]
While I did publish `0.7.10` with removed async keyword, I'll have to yank it as there is a bit of problem with actix-web dependencies

**Comment by kpp** [comment]
Try `Response::r#async(task)`

**Comment by atuk721** [comment]
Hi, ActorResponse::async is still remained.

**Comment by kpp** [comment]
You cannot use ::async as a method name in edition=2018 because it's a keyword. You have to use `Response::r#async`, 'r#' prefix allows you to use keywords as identifiers.
