### ISSUE TITLE
Actix resolver never updates from /etc/resolv.conf

### ISSUE THREAD

**Issue by cetra3** [actix/actix#202]
The actix-web client will fail to ever resolve dns names if `/etc/resolve.conf` is missing nameservers at app startup.  This is only on unix-ish systems, not sure about windows.

Steps to replicate:

* Have an actix-web application start up before the network stack is ready (or dhcp is finished).  Alternatively, muddle the `/etc/resolv.conf` to include no nameservers.
* Have that `actix-web` application make a client web request upon startup
* Fix `/etc/resolv.conf`
* Try and make another client web request
* The dns resolver will break from this point onwards, even though dns is valid.

You will see (if you have logging enabled for `trust_dns_resolver`):

```
WARN  trust_dns_resolver::system_conf::unix > no nameservers found in config
```

And then when doing subsequent connections:

```
ERROR mycrate > Error receiving versions: Failed to connect to host: Failed resolving hostname: proto error
```

I have worked around it by preventing the application from starting until resolv.conf is valid.

I don't know what the correct fix is here, but I have a few ideas:

* Check the config back from `trust-dns` to ensure there are nameservers, otherwise fail.
* Add another message type to the `Resolver` actor to allow the config to be refreshed.
* Adjust SystemRegistry to allow for actors to be removed, or recreated
* Use `tokio-dns` instead of `trust-dns` or provide a feature-gate for both.  Considering that `trust-dns` [is blocking](https://github.com/bluejekyll/trust-dns/blob/ab2533dac6afa30b0908ac0ac8d5071ba238ef74/crates/resolver/src/system_conf/unix.rs#L33) in some parts anyway.

**Comment by Patryk27** [comment]
Shouldn't this belong to the https://github.com/actix/actix-web repo?

**Comment by DoumanAsh** [comment]
resolver is part of `actix`

**Comment by robjtede** [comment]
Closing since the resolver actor is now deprecated.
