### ISSUE TITLE
Not idiomatic error handling in Actix API

### ISSUE THREAD

**Issue by ufoscout** [actix/actix#203]
Handling errors in Actix feels quite unnatural and not really compliant with the common rust approach.

In fact, most of the time, the only way of handling an error is to panic!() because the API does not accept Results as a return value.
For example, let's consider this code snippet:
```rust
fn main() {
    System::run(move || {

        // some actors started here

        // start an actix-web server
        server::new(move || {
            // create_app() returns a Result<App, SomeError>, for example it could fail to read some files
            create_app()
            // the server::new() function does not accept a Result, so we are forced to panic!
            .unwrap_or_else(|err| {
                panic!("Cannot create the webhook handlers. Err: {}", err);
            })
        })
        .bind(format!("{}:{}", bind_address, port))
        // the System::run() function does not accept a Result, so we are forced to panic! here too
        .unwrap_or_else(|err| {
            panic!("Server cannot start on port {}. Err: {}", port, err);
        })
        .start();
    });
}
```

All of this boilerplate code could be avoided, if the signature of the Actix functions was something like:
```rust
pub fn run<F>(f: F) -> Result<(), SomeError>
    where
        F: FnOnce() -> Result<(), SomeError>  + 'static
```
instead of:
```rust
pub fn run<F>(f: F) -> i32
    where 
        F: FnOnce() + 'static
```

This would allow rewriting the previous code in a much more idiomatic form:

```rust
fn main() -> Result<(), Box<std::error::Error>> {
    System::run(move || {
        server::new(move || {
            create_app()?
        })
        .bind(format!("{}:{}", bind_address, port))
        .start()?;
    })?;
}
```

The panic-based approach has many disadvantages other than difficult integration with other code and ugly use of panics. 
For example, the previous example prints a useless stacktrace if the port needed by actix-web is already in use; instead, in that case, it would be much better to print a clear "The port 1234 is not available" message to the user and simply stop the app.

**Comment by DoumanAsh** [comment]
This is a single piece of code you need to write, I don't get what's point of returning error in `run` at all, especially considering that errors are exceptional there

**Comment by DoumanAsh** [comment]
@ufoscout `actix::run` is emulated after `tokio::run` and I don't see people complaining much there.

And I don't mind single `expect` call because failing to `bind` address is anyway critical error and cannot recovered.

>the current API is not idiomatic so using it involves lots of internet searches and blog reading and so on

I have feeling this is exaggeration, but I'm here to argue about personal experience. This is not part of actix, but rather actix-web

>it is not written in stone that errors in run are exceptional.

`actix::run` expects function that returns future, it is not exactly to execute initialization code, but to bootstrap your code with just single future.

I would suggest to use full `System` if you want more control like here https://github.com/DoumanAsh/roseline.rs/blob/master/web/src/server/mod.rs#L268-L283

>a biased opinion, but all those unwrap_or_else(|err| panic!(...)) are ugly as hel

Use `expect(<text>)` for this purpose

Even when actix 0.8 would come, I have doubts about changing the semantics of `actix::run` because it is still would be used for future(and the future itself shouldn't return any meaningful results).
It is problem of current futures API and it is normal for futures APIs to be like that

**Comment by fafhrd91** [comment]
You pass factory function to the server::run, it gets executed in different threads multiple times, so you won’t get result out of run function in any case and only way to handling error there is to panic. Decision is explicit about non failable factory and api enforces that decision

**Comment by DoumanAsh** [comment]
I suspect he was talking about `actix_web::server::new`, not actix::run`

Anyway, I don't see any purpose discussing whether API is idiomatic or not, the goal of API is to be used, if you have ways to improve it then feel free to propose it.
actix is currently heavily tied to `futures` and the some parts of API are heavily mimic tokio/futures but there is nothing bad about it per se.
I don't see anything to improve here as `actix::run` is not intended to accept complex functions with lots of error handling in first place

And `System::run` is only intended as bootstrap for your actix code when you don't really want to spin own system manually.
Note that the another problem with returning error from `System::run` is that it actually starts `System` and will not stop unless you send message to stop it, so any error propagation outside of it is pointless.

**Comment by fafhrd91** [comment]
@ufoscout sorry, i misunderstood the question. you can use `.block_on()` for async initialization
