### ISSUE TITLE
Odd supervision

### ISSUE THREAD

**Issue by DGolubets** [actix/actix#204]
I was playing with supervision and it doesn't look very useful in it's current form.

This is how it works now, based on my tests:

- if there is a panic in a message handler, it still crashes the whole system
- a call to ```ctx.stop()``` or ```ctx.terminate()``` leads to the actor being restarted

I see couple of problems with that:

1. I can achieve the same without any supervisor: just add a method to reset everything in my actor and call it whenever I catch an error, skipping the whole stop-restarting part all together.
2. Using Supervisor makes it worse because I can no longer stop my actor: it always restarts no matter what. So what if it has finished it's work and no longer needed?

As of my understanding, the idea of supervision in actors starts with parent-child relationship and the fact that one actor can have multiple children. And that's where supervision becomes useful: it can stop or restart either one or all of children based on some logic.

If we take Akka as an example, it's supervision helps with error handling as well: you don't have to try\catch everything yourself - it's done by the underlying actor\system.

**Comment by DGolubets** [comment]
> In Rust panics are exceptional and are not supposed to happen. Catching panics in Rust has lots of problems on its own (mostly how unwind requirements are made)

I agree that they are not supposed to happen, but bugs are sneaky. Crashing the whole application is not always the best option. 
Consider a number of actors serving their own set of users: a bug happened in one of them doesn't necessarily mean all others are affected (they may have different algorithm settings or the bug may simple be rare). 
Using higher level tools to achieve fault-tolerance is not enough sometimes as well, e.g. if you need to start these actors dynamically, e.g. by the call to an API (I wouldn't want to integrate my app with Kubernetes API or something like that).

> At current moment Supervisor actors are supposed to be forever running alongside system.

This one is unnecessary limiting IMO.
Context could have a ```fail<E: WhateverActixError>(e: E)``` method and then Supervisor could have another one like ```decide<E: WhateverActixError>(r: Result<(), E>) -> RestartOrStopOrFail```.

> simplifies error handling

This is the part I don't understand so far.
If Supervisor doesn't do any ```catch_unwind``` internally - it doesn't help me with error handling in any way. Because I am responsible for all error handling and calling ```ctx.stop``` on top, right? 
Maybe I just miss something?

**Comment by fafhrd91** [comment]
it is not possible to unwind actix actor. this would be so intrusive in design and ergonomics would be ugly. actix wont be UnwindSafe ever

**Comment by fafhrd91** [comment]
https://doc.rust-lang.org/beta/std/panic/trait.UnwindSafe.html

btw Rc/Arc are not UnwindSafe
