### ISSUE TITLE
Is it possible to depend on inner future in Handler::handle?

### ISSUE THREAD

**Issue by najamelan** [actix/actix#205]
I try to use actix to build an application, but I'm struggling. One of the specific questions I have. I make an actor responsible for dealing with a connection. If I understand well, Actor.send is async, but if in the handle function I would use sync io, it would block the thread. 

So I would like to use async io, but I can't return Async::NotReady from Handler::handle right? Even though Actor.send returns a future, handle is not the poll function of that future? Also I cannot use await! on other futures, and I also tried returning a Boxed future from handle, but the compiler says it can't be send accross threads...

So how do I wait for an inner future to complete and be polled again?

**Comment by najamelan** [comment]
I also tried to make an async block and use tokio::spawn, but then it's definitely multithreaded and the result (connection handle) of the inner future needs to be saved in the actor for future message handling (Write message) to write to the stream... So that would mean sending &mut self of the actor protected by a mutex or something, but I don't even know if that would be possible...

**Comment by DoumanAsh** [comment]
You can return future from your handler. My example https://github.com/DoumanAsh/roseline.rs/blob/master/actors/src/exec.rs#L618-L638

If your message handler needs to be perform CPU bound job, use `SyncArbiter` to start actor

Please use gitter for such queries

**Comment by najamelan** [comment]
Thanks, the code you showed me helped to figure out some things. I didn't realize that the Result type on Message could be different than on Handler. I relooked at the book and I had forgotten about the MessageReponse trait, so that's interesting too. So I can return futures.

I haven't found a convenient way to run other async operations from within "handle". Especially when the result of the operation needs to be saved on the actor... I wonder if it would be possible to create an AsyncHandler trait which has `async fn handle`. I will give it a try.
