### ISSUE TITLE
Why is SystemService bound by Default?

### ISSUE THREAD

**Issue by rjsberry** [actix/actix#210]
Hi. I'm really enjoying developing with actix, thanks for all your hard work!

I'm struggling to understand why `SystemService` requires the `Default` bound.

Requiring an actor to implement `Default` in order to implement `SystemService` means that I can't really use any complex actors that simply don't/can't implement `Default`. From an architectural standpoint having core actors that are always going to be alive for the duration of my program implement `SystemService` greatly reduces the complexity in communication with them from other actors as they can always access their address via the system registry.

It's entirely possible to work around this trait bound with a divergent `Default` impl and echoing the actor creation function found in `SystemService::start_service` with an alternative complex constructor.

```rust
use actix::prelude::*;

struct Foo { /* stuff that can't implement Default... */ }

impl Foo {
    fn new(/* potentially complex construction... */) -> Self {
        Self {}
    }
}

impl Default for Foo {
    fn default() -> Self {
        unimplemented!()
    }
}

impl Actor for Foo {
    type Context = Context<Self>;
}

impl Supervised for Foo {}

impl SystemService for Foo {}

fn main() {
    actix::System::run(|| {
        Supervisor::start(|ctx| {
            let mut act = Foo::new(/* requires information collected at runtime... */);
            act.service_started(ctx);
            act
        });
    });
}
```

I can't help but feel like this is either a misuse of system services, or that I'm really having to work against actix here.

`Default` is obviously used to construct the actor in [`SystemService::start_service`](https://github.com/actix/actix/blob/d28d286ac652f81e72c2aa413e7c0d3fc6c6099c/src/registry.rs#L232-L238). If this was its only use I would suggest we consider a `start_service_with` function along the lines of:

```rust
fn start_service_with(f: impl Fn() -> Self) -> Addr<Self> {
    Supervisor::start(|ctx| {
        let mut act = f();
        act.service_started(ctx);
        act
    })
}
```

Users could then move data that has been gathered into this closure in order to construct the actor.

However, with the current ergonomics of the `SystemRegistry::get` I don't think this is a viable solution. `SystemRegistry::get` relies on being able to construct an instance of the system service actor with no additional information which is the reason I presume there is a bound on `Default` in the first place.

What's the best way to deal with complex actors that need to be accessed system wide?

**Comment by rjsberry** [comment]
> `Default` is necessary for service precisely because it should possible to start service without external data(from `SystemRegistry`)

So currently there are no plans for configurable system services in actix without the workaround I posted above?

**Comment by wenig** [comment]
Did anything happen here? I have the same issue!

**Comment by juchiast** [comment]
Is there plan to revisit this? I think an actor with no configurable options isn't very useful.

**Comment by Sytten** [comment]
Actix is in maintenance mode so unlikely
