### ISSUE TITLE
Future, intended use case, development and support guarantees 

### ISSUE THREAD

**Issue by SRGOM** [actix/actix#212]
This is an open source project and I don't want to be looking a gift horse in the mouth but I am keen to use this library and am interested in understanding it's future directions and support guarantees.

I have learnt, from hearsay mostly, that this is used for Azure IOT. I was looking at some benchmarks yesterday and this seems crazy performant. 

I do not see much of this in the README so figured I would ask a question-

1) Where is this project used? 

2) Does Microsoft intend to sell this to clients in some form? Say how they sell Powershell? 

3) Will there be any paid support? 

4) What are the dev guarantees on this project? 

5) What is the direction, are you intending to git a 1.0.0 sometime- where you are reasonably confident that this is stable? Or is this good enough for your use case right now- the crashes and bugs you may or may not run into are not relevant to your use case?

Once again, I know this is free and I'm putting a burden on you by asking this question but I'd love to hear where you guys are going...

Thank you.

**Comment by fafhrd91** [comment]
actix org contains several subprojects, actix - actor system, actix-web - http/web framework, actix-net - framework for networking services. 

i dont use actors system in my day to day job, as it introduce too much overhead for our use case.
other than that actix is open source and has specific license everything else is outside of the project.

**Comment by DoumanAsh** [comment]
I cannot answer all questions but:

>2. Does Microsoft intend to sell this to clients in some form? Say how they sell Powershell?

The project is going to be open source and free. Both `actix` and `actix-web`

>5. What is the direction, are you intending to git a 1.0.0 sometime- where you are reasonably confident that this is stable?

It cannot be `1.0.0` until tokio stabilizes with futures

**Comment by SRGOM** [comment]
Thank you that both of the lead contributors decided to respond. And thank you all of you guys for creating this amazing software (at least in benchmarks, haven't used the API much)

So- no roadmap either, I take it?

**Comment by DoumanAsh** [comment]
There are no plans per se. I have some ideas, but nothing that would involve significant changes to `actix`

**Comment by SRGOM** [comment]
Thanks DoumanAsh. This answers my question. I look forward to you and other community taking actix forward. I do think that since Actix is the fw of choice in rust right now for both actors and web, this would se  a lot of improvement.
