### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by dantodor** [actix/actix#219]
Hello!

I just started learning Rust a couple of weeks ago. So please excuse me if my question falls in the stupid category.
I worked a lot with Akka on the JVM and with Elixir on the beam, so I was very happy when I found Actix on Rust. I implemented a short worker pull system, in which I spawn a number of workers, register them to a coordinator and let them ask for and do some work. To my surprise, performance was worse than a single-threaded approach. So, by giving it enough work, I was able to see that it loads one core out of 8 to 100%, the rest being idle. I can reproduce the same behavior on the ring example, by giving large enough values, like 1000 nodes and 10000 times.
Is this expected behavior or am I doing something wrong ? The tokio runtime isn't using by default all the cores available ? 
Thanks!

**Comment by DoumanAsh** [comment]
Internally `actix` uses single threaded tokio event loop, if all of your work is done in `Future` then you're going to pull all this work there when you're using regular async actors.

I suggest to hit [gitter](https://gitter.im/actix/actix) and ask people around.
If you don't need async IO then something like `riker` might be closer to regular actor system

**Comment by dantodor** [comment]
Thanks for your answer.
