### ISSUE TITLE
No way to flush FramedWrite streams?

### ISSUE THREAD

**Issue by Sushisource** [actix/actix#227]
I have an actor which reads from TCP using `add_stream` and `StreamHandler`. It also owns a `FramedWrite<WriteHalf<TcpStream>, SomeCodec>`, which it often writes to inside of the `StreamHandler`. Stopping the actor can leave unsent messages in that write stream -- I can understand that simply stopping the actor, it wouldn't necessarily know how to flush the stream. Hence, seems like there should be a flush method available on `FramedWrite`.

I think this relates heavily to #132 which would also help a lot.

EDIT: I'd also expect `.close()` on the framed write to flush, but it doesn't appear to.

**Comment by DoumanAsh** [comment]
@fafhrd91 Should we add option for manual flush? Or should it maybe called in destructor?

**Comment by Firstyear** [comment]
manual flush seems like it could handle more diverse cases than only flushing in the destructor. I think both would be good to have in this case?

**Comment by Sushisource** [comment]
I'd go for both personally. I'm happy to look into making a PR tomorrow if you're open to a contribution here.

**Comment by fafhrd91** [comment]
@DoumanAsh i think it is fine

**Comment by DoumanAsh** [comment]
@Sushisource if you're going to work on it, please note that we now have `0.8` on master and separate branch on `0.7`

**Comment by Sushisource** [comment]
@DoumanAsh Sounds good - I'm fine with it going into either personally, if 0.8 is gonna be released relatively soon. I'm happy to do it wherever is easiest

**Comment by Sushisource** [comment]
Looked into this briefly today. The problem seems to be that in order to flush the `AsyncWrite`r inside of the `FramedWrite`, you need to be able to force a `poll` of the `WriterFut` which is spawned when a `FramedWrite` is created. Problem is it's not clear how to do that. The `SpawnHandle` seemingly can't be used for that purpose. I also tried having the caller pass in the context, and using that to wait on an identically constructed `WriterFut`, but that didn't result in poll being called either.

Any thoughts on that?

**Comment by DoumanAsh** [comment]
@Sushisource I already added my comment in PR but to just clarify.
I think generally flush should remain async and you only need to notify `WriteFut` task to force data write and flush.
Since writer is async, it can would block and you will not be able to handle it properly in sync code, so better to leave it for `WriterFut::poll`

As for destructor we can just add write of remaining data and flush unconditionally(ignoring errors) in hope that it will be able to write it all
