### ISSUE TITLE
Context.wait does not spawn futures

### ISSUE THREAD

**Issue by s-panferov** [actix/actix#235]
My handle code looks like this:

```rust
let fut = client
    .prepare(&sql)
    .into_actor(self)
    .map(|st, _a, _c| {
        println!("Request ok");
        ()
    })
    .map_err(|e, _a, _c| {
        println!("Reqest error: {:?}", e);
        ()
    });

ctx.wait(fut);
```

And it does not work (I don't see "Request ok"). But if I replace the last line with `ctx.spawn(` then it starts to work like charm. I believe `ctx.wait` is broken

**Comment by DoumanAsh** [comment]
Are you sure that wait blocks forever?
I'm pretty sure it is used in various instances else where, including our examples and unit tests.
I doubt it would block indefinitely as otherwise your future would never actually resolve even with `spawn`

**Comment by s-panferov** [comment]
It does not block the current thread, it just doesn't spawn futures as `ctx.spawn` does.

**Comment by DoumanAsh** [comment]
I don't follow you.

What do you mean it doesn't spawn future?
The only difference between `spawn` and `wait` is that wait futures are being processed before any other events (incoming messages and spawned futures)

**Comment by s-panferov** [comment]
@DoumanAsh sorry, I don't know yet how actix works internally and what is really going on, I'm just a newbie user and trying the library. From my perspective, everything works when I invoke `ctx.spawn` and stop working when I replace it with `ctx.wait`. I expected no difference between these two methods in the current context.

I can try to create a reproduction example if the provided information is not enough.

**Comment by rivertam** [comment]
@s-panferov I think creating a reproduction example is a good idea regardless. It may help you figure it out yourself. =) And then either we can add it as a test to make sure the problem stays solved (if it is a problem), or we can add it as an example for documentation purposes if it's not a problem and it helps clarify things.

**Comment by DoumanAsh** [comment]
@s-panferov Yes, if possible I'd appreciate example to try and debug it myself.
Though I have feeling it might be related to database driver

**Comment by s-panferov** [comment]
https://github.com/s-panferov/actix-repr here is the short version of my code. To properly run this project you need a PostgreSQL instance:

```bash
docker run --name actix-postgres -e POSTGRES_PASSWORD=123456 -p5432:5432 -d postgres
```

**Comment by DoumanAsh** [comment]
Uhhh having a need to install PostgreSQL doesn't make it easy for me on Windows...

Oh well I'll see to it, thx

**Comment by s-panferov** [comment]
@DoumanAsh isn't docker available on windows?

**Comment by DoumanAsh** [comment]
Last time I used it, it was constantly crashing my PC

**Comment by DoumanAsh** [comment]
Can you please clarfiy do you see the println [here](https://github.com/s-panferov/actix-repr/blob/master/src/main.rs#L31) and/or [here](https://github.com/s-panferov/actix-repr/blob/master/src/main.rs#L33)

Or you do not see it [here](https://github.com/s-panferov/actix-repr/blob/master/src/main.rs#L69)?

**Comment by s-panferov** [comment]
If `ctx.spawn` is used I see "Postgres connected!" and then "Request ok". If `ctx.wait` is used, don't see the "Request ok".

**Comment by DoumanAsh** [comment]
Can you change [here](https://github.com/s-panferov/actix-repr/blob/master/src/main.rs#L34) to `ctx.wait` too and see if it behaves differently?

**Comment by s-panferov** [comment]
@DoumanAsh I see only "Postgres connected!" as expected (`Init` message processing is blocked), because the `connect` future in tokio-postgres never resolves by design.

**Comment by DoumanAsh** [comment]
I think you should spawn connect future using `Arbiter::spawn` because `Context::wait` prevents us from polling `Context::spawn` items

**Comment by s-panferov** [comment]
@DoumanAsh yes, it works this way. Thanks for your time, I appreciate it! This behavior is not obvious from the docs though, I'll try to prepare a PR with the clarification.

**Comment by DoumanAsh** [comment]
@s-panferov if you take a closer look it says `This stops processing any incoming events until the future resolves.`

But we can further clarify it with examples such as message or `Context::spawn` futures
