### ISSUE TITLE
try_send less usable with Failure style errors after 0.8

### ISSUE THREAD

**Issue by Sushisource** [actix/actix#249]
This change:

https://github.com/actix/actix/commit/1755ee25f66bcbd52bff539b76d5eecb29b697a8#diff-b18cf37ebefb4a196f97752ee1f1ac27L59

Removed the ability to easily use `?` on `try_send` in handlers that return a `failure::Error` - this was really nice to have. Is there any particular reason that needs to be gone? Can we re-introduce it, or add a `std::Error` impl?

**Comment by DoumanAsh** [comment]
We can add `std::error::Error` but we don't need `failure`

**Comment by Sushisource** [comment]
Makes sense. Opened PR.

**Comment by DoumanAsh** [comment]
Closing it as it is merged
