### ISSUE TITLE
Send message to a group of actorx

### ISSUE THREAD

**Issue by ufoscout** [actix/actix#256]
I wonder if there is a way to send a single message to more than one actor.

For example, I have a set of sync actors:
```rust
 let addr = SyncArbiter::start(8, move || MyActor {
            config: init_config()
        });
```
at runtime, I need to send a message to all the instances of _MyActor_ to notify them to update their configuration but I can't figure out how to achieve it.

I know that I could do:
```rust
let config = Arc::new(RwLock::new(init_config()));
 let addr = SyncArbiter::start(8, move || MyActor {
            config: config.clone()
        });
```
so whatever actor can update the shared config; however, I would like to avoid the overhead of the Arc and the locks.

**Comment by DenSASoftware** [comment]
There is the actix-broker-crate that allows you to publish and subscribe to messages based on their type.

You could create a type like struct ConfigUpdate(Config); to hold your updated configuration and publish it ("issue" it, following the crates terminology) while your actors subscribe to that type of message.

**Comment by naturallymitchell** [comment]
should [Actix-Broker](https://github.com/chris-ricketts/actix-broker) merge into Actix Core?

**Comment by fakeshadow** [comment]
Sorry you can not have the cake and eat it.
SyncActors use crossbeam channel for sending message to multiple instances of same actor. There is no tell which one would get the message as that's the point of it. You have use locks(or thing alike) or clonable message to broadcast something to all of them.

**Comment by robjtede** [comment]
actix-broker is an @actix project now too
