### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by DGolubets** [actix/actix#26]
In this simple example an actor sends a message to itself repeatedly.

I would assume a constant memory usage here. However it keeps growing.

Maybe I missed some important detail from the docs or it's leaking somewhere.

```
extern crate actix;

use actix::*;

struct CounterActor;

struct Count {
    pub i: u32,
    pub sender: Address<CounterActor>
}

impl ResponseType for Count {
    type Item = u32;
    type Error = ();
}

impl Actor for CounterActor {
    type Context = Context<Self>;
}

impl Handler<Count> for CounterActor {
    fn handle(
        &mut self,
        msg: Count,
        ctx: &mut Self::Context,
    ) -> Response<Self, Count> {
        msg.sender.send(Count { i: msg.i + 1, sender: msg.sender.clone() });
        println!("{}", msg.i);
        Self::reply(msg.i)
    }
}

fn main() {
    let system = actix::System::new("test");

    let addr: Address<_> = CounterActor.start();

    addr.send(Count { i: 0, sender: addr.clone() });

    system.run();
}

```

**Comment by fafhrd91** [comment]
interesting! I guess something is leaking.

**Comment by fafhrd91** [comment]
it might be message processing loop in context's pool, it probably never returns from pool method. I need to check

**Comment by DGolubets** [comment]
Yeah, you are right. 
It is ActorAddressCell::poll's loop.

I think solution is very simple: just break the loop after some number of iterations (should be configurable by user, ideally, with reasonable default). Then it will proceed to items poll and they will not stack forever anymore.

I didn't get myself 100% familiar with all internals yet, let me know if you think this is correct way of solving it (at least tests worked). I can make a PR later if you want.

**Comment by fafhrd91** [comment]
Thanks for the PR!
