### ISSUE TITLE
Is it possible to fixed the Addr type ?

### ISSUE THREAD

**Issue by sunhuachuang** [actix/actix#261]
If the Addr type is fixed, and not dependent on Actor, so that Addr can be put into a list, and many different Actors can be managed and deployed at the same time.

Example:
```rust
let actors: HashMap<u64, Addr> = HashMap::new();
actors.insert(0, addr1); // CatActor
actors.insert(1, addr2); // DogActor
actors.get(0).as_ref().unwrap().do_send("Meow ~")
actors.get(1).as_ref().unwrap().do_send(”Bow-wow")
```
and, I think it maybe better for impl remote actor.

**Comment by fafhrd91** [comment]
it is not possible, you can try `Recipient<M>`

**Comment by sunhuachuang** [comment]
Awesome, `Recipient<M>` can solve the scene I said, Thx.
