### ISSUE TITLE
Error: Mailbox has closed when using actix_web

### ISSUE THREAD

**Issue by komaeda** [actix/actix#263]
While using actix-web with actix, after renaming the directory my code is in, I suddenly got this error:

```
[2019-06-16T15:04:32Z ERROR actix_web::pipeline] Error occurred during request handling, status: 500 Internal Server Error Mailbox has closed
```

By itself, is there any way to fix this error? I'm assuming it's somehow related to two threads trying to communicate, but there shouldn't be anything that prevents them from doing so?

**Comment by fafhrd91** [comment]
this error means your actors died

**Comment by komaeda** [comment]
> this error means your actor died

do you know what possible causes that could have? :fearful:

**Comment by fafhrd91** [comment]
It is your code. How would I know?

**Comment by komaeda** [comment]
the strange thing is that I changed nothing about my code (except for renaming the directory it's in) between it working and this error popping up, which is why I was hopeful there would be some sort of generalized solution, but no such luck I guess.
