### ISSUE TITLE
the url for 'signal' in README.md is broken

### ISSUE THREAD

**Issue by howaboutsynergy** [actix/actix#267]
> More information on signal handling is in the [signal](https://actix.github.io/actix/actix/actors/signal/index.html) module.

https://github.com/actix/actix/blob/c3c7af2bde0c9f8ad4d97da5241b15810d9f139d/README.md

Where can I find that doc?
I got to [here](https://docs.rs/actix/0.8.3/actix/actors/index.html) but it's not there.

**Comment by JohnTitor** [comment]
According to CHANGES.md, the signals actor was deleted in `0.8.0-alpha.1` (https://github.com/actix/actix/blob/master/CHANGES.md#080-alpha1-2019-03-28).
You can use `tokio-signal` instead and [the chat example](https://github.com/actix/actix/blob/74f50c6d35aa1a0f70cf1102e60dc3b6e2f02203/examples/chat/src/main.rs#L74-L82) seems good one to refer.
But yes, we should update README to avoid confusion.
