### ISSUE TITLE
how to broadcast a message to all SyncContext actors in a SyncArbiter pool

### ISSUE THREAD

**Issue by jvo203** [actix/actix#271]
At present I am using a SyncArbiter to start a pool of SyncContext-based SessionSever actors:

let server = SyncArbiter::start(num_workers, || server::SessionServer::default());

Executing server.do_send(some_custom_message) sends a message to only one arbitrary actor from the pool. How do you broadcast a message to all SyncContext actors in the SyncArbiter pool?

**Comment by fafhrd91** [comment]
It is not possible.

**Comment by jvo203** [comment]
Thank you for a very prompt answer.
