### ISSUE TITLE
Standard way to get actor addr inside another actor

### ISSUE THREAD

**Issue by PlaneB** [actix/actix#286]
When I start a few actor say in main, then I have all their addresses in. But those addresses are needed inside every actor. 

What is the standard/best practise way to get actors to communicate with each other using the addresses? Unfortunately I can not deduce this from the examples.

**Comment by markhildreth** [comment]
I'm not sure about standard/best practice, and I'll leave that for others to comment on. I had a similar question a few weeks ago and I'll report what I found.

First, you can register any actor as a service using a [registry](https://actix.rs/actix/actix/registry/index.html). This allows arbitrary actors to find the "service" actor quite easily. Once one actor finds the other, it can send a message with its own address to allow messages to be sent in the opposite direction as well.

Another option is to start one actor inside of another. In that situation, the "parent" actor can give its address to the child when starting it, and can get the child's address as a result of calling `start`.

Finally, if you want to ensure both actors are created at the same time with each other's address, you can use [`Actor::create`](https://actix.rs/actix/actix/trait.Actor.html#method.create). This gives you a way to have access to the context of an actor while you create it, which means you get access to the address during that time. For example...

```rust
ActorA::create(|ctx: &mut Context<ActorA>| {
  let addr_a = ctx.address();
  let addr_b = ActorB { addr_a }.start();
  ActorA { addr_b }
});
```

**Comment by PlaneB** [comment]
Good findings thanks! However its a bit strange that there is no standard way, because this is somtehing almost every implementation will face at some point, except of toy or fringe examples, IMHO.
