### ISSUE TITLE
Expose the Framed underneath FramedContext

### ISSUE THREAD

**Issue by str4d** [actix/actix#29]
I have the following transport flow:

- Server receives incoming stream (or client makes outgoing connection).
- `Framed` is used with `InboundHandshakeCodec` (or `OutboundHandshakeCodec`) to perform a protocol handshake.
- A new `Framed` is created with a general post-handshake `Codec` via:

      let (parts, handshake_codec) = handshake_framed.into_parts_and_codec();
      Framed::from_parts(parts, Codec::from(handshake_codec))

This is necessary because `Codec` needs to grab encryption setup information from `*HandshakeCodec`.

Looking at the code, `FramedActor::framed(stream, InboundHandshakeCodec)` passes its arguments through to `FramedContext::new()`, which calls `stream.framed(codec)` and stores the result internally. It would be great to have a `FramedContext` method that kills it and returns the underlying `framed`, and a corresponding `FramedActor::framed()` equivalent that takes a `Framed` instead of `stream, codec`.

**Comment by fafhrd91** [comment]
added in 07aaf13

**Comment by fafhrd91** [comment]
0.3.5 version is released
