### ISSUE TITLE
how to send message to another actor and wait for the response in actor's handle method?

### ISSUE THREAD

**Issue by pangwa** [actix/actix#291]
Hello,

How to send a message from actor a to actor b, and wait for the result from b?

I got a deadlock with the wait() call. 

```rust
pub struct ActorB {
}
impl Actor for ActorB {
    type Context = Context<Self>;
}
struct MessageB {
}

impl Message for MessageB {
    type Result = Result<String, Error>;
}


pub struct ActorA {
   pub actor_b: Addr<ActorB>,
}

struct MessageA {
}

impl Message for MessageA {
    type Result = Result<String, Error>;
}

impl Handler<MessageA> for ActorA {
    type Result = Result<String, Error>;

    fn handle(&mut self, msg: MessageA, _ctx: &mut Context<Self>) -> Self::Result {
      self.actor_b.send(MessageB{}).wait()?? // deadlock here, how to wait for message response from actor b?
    }
}

```

**Comment by thedodd** [comment]
The deadlock is because both of your actors are running on the same thread, and your call to `.wait()` is blocking the thread waiting for a response, but because of the fact that the thread is now blocked, the executor can not swap over to make progress on the other future. 

A few things you need to do:
- because communication between the actors is based on futures, your response type for the `Handler<MessageA>` must be some sort of future. Have a look here: https://docs.rs/actix/0.8.3/actix/type.ResponseFuture.html that is probably what you want to use.
- once you've converted the response type, remove the `.wait()??`, and it should just work. ** You may need to put some combinators in place to extract the appropriate value, but the compiler will show you what to do. Probably just: `self.actor_b.send(MessageB).and_then(|res| res)`, but you'll have to test.

**Comment by pangwa** [comment]
Thanks!, I finally made it work using ctx.wait() and future::shared(). 

The goal is to make the actor returns a future and the actor handles next message only after the future resolves. 

I used ctx.wait() to wait for the future complete. And create a shared future to use in ctx.wait() and return the future value. Am I doing it right? 

```rust

pub struct TestMsg {
    pub id: i32,
}

impl Message for TestMsg {
    type Result = Result<i32, ServiceError>;
}

impl Handler<TestMsg> for OrderActor {
    type Result = ResponseActFuture<Self, i32, ServiceError>;

    fn handle(&mut self, msg: TestMsg, _ctx: &mut Context<Self>) -> Self::Result {
        info!("handling message: {}", msg.id);

        let when = Instant::now() + Duration::from_millis(5000);

        let task = Delay::new(when)
            .map_err(|_| ServiceError::InternalServerError)
            .and_then(move |_| {
                info!("done timer: {}", msg.id);
                Ok(msg.id + 1)
            }).shared();

        let f = task.clone();

        let u = f.map(|_| ()).map_err(|_| ());
        _ctx.wait(u.into_actor(self));

        Box::new(task.clone().map(|v| *v).map_err(|e| ServiceError::InternalServerError).into_actor(self))
    }
}


```

> The deadlock is because both of your actors are running on the same thread, and your call to `.wait()` is blocking the thread waiting for a response, but because of the fact that the thread is now blocked, the executor can not swap over to make progress on the other future.
> 
> A few things you need to do:
> 
> * because communication between the actors is based on futures, your response type for the `Handler<MessageA>` must be some sort of future. Have a look here: https://docs.rs/actix/0.8.3/actix/type.ResponseFuture.html that is probably what you want to use.
> * once you've converted the response type, remove the `.wait()??`, and it should just work. ** You may need to put some combinators in place to extract the appropriate value, but the compiler will show you what to do. Probably just: `self.actor_b.send(MessageB).and_then(|res| res)`, but you'll have to test.

**Comment by thedodd** [comment]
If your goal is to emulate pipelining / queueing, I would recommend using a stream as the queue and just have your actor impl StreamHandler for the stream's message type. That will allow your actor to fully finish processing each element of the stream before moving on to the next element in the stream. This will also allow the actor to concurrently handle other message types as well.

**Comment by pangwa** [comment]
thanks! Looks like StreamHandler could be used in my case. I'll take a try!

**Comment by frol** [comment]
Is there an approachable example of pipelining with StreamHandler API? I need to implement a custom protocol on top of WebSocket, which is implemented with StreamHandler API, so I, basically, need to delegate the incoming messages to the Codec Stream, and then to the Application Protocol Stream, which in turn produce 0 or more (potentially even infinite) responses.
