### ISSUE TITLE
0.8.x leads to panic on startup when mixing with actix-web 2

### ISSUE THREAD

**Issue by samsieber** [actix/actix#299]
I was trying out the 2.0 alpha of the actix-web crate, and when I include the 0.8.3 release of actix it leads to a panic on startup because actix 0.8 and actix-web 2 use different versions of actix-rt. 

Is it in the roadmap to update to a later version of actix-rt?

**Comment by JohnTitor** [comment]
Actix-web 2.0 contains breaking change (mainly std::future migration) so you can't use it with Actix 0.8. See also #298, you can see the progress of this migration.
Closing this issue due to dup of the above issue.
