### ISSUE TITLE
Errors when compiling actix-web 1.0.9

### ISSUE THREAD

**Issue by uvarovdm** [actix/actix#302]
Hello, could you please help me the below compile issue.
rustc 1.39.0 (4560ea788 2019-11-04)
actix-web = "1.0.9"
```
error: macro expansion ignores token `if` and any following
   --> <::log::macros::log_impl macros>:13:23
    |
13  |       let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
    |                         ^^
    | 
   ::: /home/uvarovdm/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.7.4/src/rr/domain/label.rs:248:17
    |
248 | /                 debug!(
249 | |                     "xn-- prefixed string did not translate via IDNA properly: {:?}",
250 | |                     e
251 | |                 )
    | |                 -
    | |                 |
    | |_________________caused by the macro expansion here
    |                   help: you might be missing a semicolon here: `;`
    |
```

**Comment by fafhrd91** [comment]
publish your repo, otherwise it is hard to tell what is the problem

**Comment by uvarovdm** [comment]
The project is just a "hello world" example program with just one dependency (actix-web="1.0.9"). Okay, it looks like the problem has disappeared after I changed `actix-web = "1.0.9"` to `actix-web = "*"`. What is weird that even if I change it back now to `actix-web = "1.0.9"` (and doing cargo clean and cargo update) it still compiles successfully, so I can't reproduce the issue.

**Comment by JohnTitor** [comment]
It's just a temporary issue, I guess. Anyway, I will close this issue, thanks for the report!
