### ISSUE TITLE
Decouple actix-http dependency

### ISSUE THREAD

**Issue by dunnock** [actix/actix#321]
There is circular dependency: actix -> actix-http -> actix-web -> actix , which makes it hard to update versions. This crate depends on actix-http only because of 2 implementations:

 - https://github.com/actix/actix/blob/ba9f0a374462b80374ab9ecf5956c4a1265e7a87/src/lib.rs#L208
 - https://github.com/actix/actix/blob/ba9f0a374462b80374ab9ecf5956c4a1265e7a87/src/actors/resolver.rs#L151

What about moving those implementations to actix-http crate and remove actix dependency on actix-http breaking the loop.

**Comment by dunnock** [comment]
Made change to remove `http` feature in a branch https://github.com/dunnock/actix/tree/actix-decouple-321 . Since it is breaking change I guess it should go to the new branch and 0.10-alpha, can you pls create one?

**Comment by JohnTitor** [comment]
Uhm? I think it won't break build so you can submit a PR directly. We already have `0.9` branch so the non-breaking fix will be backported there.

**Comment by dunnock** [comment]
Yes it does not seem that it will break API, though if somebody had in dependencies `actix = { version = "0.9", features = [ "http" ] }` their build will fail with error that crate does not have such feature anymore. I guess should we keep the feature in the crate as noop for build back compatiblity?

**Comment by JohnTitor** [comment]
I won't make a release in 0.9 with a breaking change so it doesn't matter.
