### ISSUE TITLE
HTTP Referer in Actix

### ISSUE THREAD

**Issue by hyousef-rusty** [actix/actix#330]
In my application, I want to give access for running a given video based on user subscription, and do not want to allow any user to download it.  
To allow video to be played in element from my PHP website, but not allowing it through direct link, I created `.htaccess` in a sub-directory with the source videos, and nothing else. with the below code:

```php
RewriteEngine On
RewriteCond %{REQUEST_URI} \.(mp4|mp3|avi)$ [NC]
RewriteCond %{HTTP_REFERER} !^http://sample.com/.*$ [NC]
RewriteRule ^.* - [F,L]
```
I need to do the same with `actix` server, but do not know how?

**Comment by leizzer** [comment]
This doesn't look like a issue. It's a request for help building a service.
You can find people that could help you on Gitter https://gitter.im/actix/actix

Clossing this ticket

**Comment by Jonathas-Conceicao** [comment]
It's also worth pointing out that there's a https://gitter.im/actix/actix-web more suited for questions regarding `actix-web`, the web framework.
