### ISSUE TITLE
Actix 0.10 roadmap

### ISSUE THREAD

**Issue by JohnTitor** [actix/actix#337]
Rough thoughts:

- [x] #324 
  - [x] update `trust-dns-resolver` to 0.19.0 or higher (#345)
- [x] #335
- [x] #405 make `Request` `Send`

(deferred to later release) #314 (https://github.com/actix/actix/issues/337#issuecomment-652185348)

**Comment by ignatenkobrain** [comment]
Would be very nice if you could update trust-dns-resolver to 0.19+ ASAP since actix stack is broken in Fedora right now due to that.

**Comment by JohnTitor** [comment]
v0.10.0-alpha.1 is released, let's see if there are any fallout.

**Comment by raultang** [comment]
Greeting, would this one https://github.com/actix/actix/issues/314 be considerable of 0.10 roadmap, as of upgrading from 0.8 the map_err and and_then was removed since 0.9.

**Comment by robjtede** [comment]
In the interests of having stable dependencies for actix-web v3 crates we're going to go ahead and push the try extensions traits enhancement to a later release to give it a proper testing cycle.

**Comment by robjtede** [comment]
v0.10.0 is out! Thanks to all involved making this release happen <3
