### ISSUE TITLE
documentation in docs.rs "hides" some relevant sample code

### ISSUE THREAD

**Issue by horacimacias** [actix/actix#342]
Not sure if this is a problem in the actix documentation or on docs.rs but some of the currently available documentation does not display commented out code.

For example:

https://docs.rs/actix/0.9.0/x86_64-apple-darwin/actix/fut/trait.ActorFuture.html

shows the following:

![image](https://user-images.githubusercontent.com/1333208/74640265-8acafd00-516f-11ea-99ad-3de968622f6d.png)

however the source code contains more, just commented out.

![image](https://user-images.githubusercontent.com/1333208/74643224-a71d6880-5174-11ea-9514-53eed7280924.png)

**Comment by JohnTitor** [comment]
We generally show a minimal example, not entire code in docs.rs since it's verbose as an example. That's why some items are commented out. But indeed this isn't ideal, we should also comment out blank lines.

**Comment by horacimacias** [comment]
ah ok, so this hiding is intentional; I'm a rust newbie and was confused about that.

Well, if this is intentional that's fine, just cleaning up extra lines may help but I see it's not a big deal.
I'll make sure to check source code directly next time :)

thanks for the fast answer!

**Comment by Jonathas-Conceicao** [comment]
Spaces there has been cleared on a recent pr (#326), should be visible in the doc.rs on the next release.

**Comment by JohnTitor** [comment]
v0.10.0-alpha.1 is out, closing.
