### ISSUE TITLE
`ActorStream` blocks other tasks in the same thread until `ctx.waiting()` returns `true` or the `Stream` is pending.

### ISSUE THREAD

**Issue by masnagam** [actix/actix#360]
## Version

* actix v0.9.0

## Platform

* any

## Description

`ActorStream` blocks other tasks in the same thread until `ctx.waiting()` returns `true` or the `Stream` is pending.
https://github.com/actix/actix/blob/master/src/stream.rs#L137

If the `Stream` can keep providing items for a long time, other tasks have no chance to run unless `ctx.wait()` is called in `StreamHandler::handle()` .
https://github.com/masnagam/rust-case-studies/blob/master/actix-actor-stream-hang/src/main.rs#L13

The asynchronous task system used in Rust is some kind of [cooperative multitasking system](https://en.wikipedia.org/wiki/Cooperative_multitasking).  So, I think that it might be better to provide a method to voluntarily yield control.

At this point, `ctx.wait(actix::fut::wrap_future(actix::clock::delay_for(Duration::from_secs(0))))` is one of ways to pause the context and yield control.

A similar situation occurs in other types. For example:
https://github.com/actix/actix/blob/master/src/mailbox.rs#L89

**Comment by Jonathas-Conceicao** [comment]
The way we `poll` the `Stream` seams right to me, as we will ensure we consume all currently available data when polling the stream. Same goes for the `Mailbox` as we can ensure all messages get spawned.

If I get it right, your point is that we should offer a better way to yield control when handling a infinite stream? I see how this can be a valid use case and we should offer better support for it. Using `ctx.wait(tokio::task::yield_now().into_actor(self));` also does the trick, having a `yeld_now` method for `AsyncContext` semas good to me, I'll look into it, but I wanna be sure I got right the problem you're reporting.

**Comment by masnagam** [comment]
Thank you for your quick reply.

> we should offer a better way to yield control when handling a infinite stream?

No.  The current implementation is acceptable to me when handling an infinite stream.  For simplicity, I used `futures::stream::repeat()` in the example.

I'm thinking of a case where there are many items in the buffer of the stream object.  In this case, the `ActorStream::poll()` blocks for a long time.  This might cause an issue if there are other higher priority async tasks than it in the same thread.

> Using ctx.wait(tokio::task::yield_now().into_actor(self)); also does the trick

I confirmed that it works fine, too.  I updated the example in github.

**Comment by Jonathas-Conceicao** [comment]
@masnagam pr #363 should make actor still responsive when handling very large streams. Would be nice if you could confirm that works for you too.

I couldn't think of any practical use case where the `loop` on `Mailbox::poll` would be too problematic, so I'll ignore that for now as it can be a little bit trickier to solve. Let me know if you have a reproducible example to illustrate that too.

**Comment by masnagam** [comment]
@Jonathas-Conceicao Thank you for taking the time to this issue.

> Would be nice if you could confirm that works for you too.

Sure.  I'll check that with my application.

> I'll ignore that for now as it can be a little bit trickier to solve.

I agree with your opinion.
I believe that incoming messages/second is much less than streams.

**Comment by masnagam** [comment]
Confirmed that `Jonathas-Conceicao:topic/non_blocking_stream_handler` works fine as before.

**Comment by masnagam** [comment]
There were similar issues in tokio.  tokio introduced an opt-in module `preemption` to avoid starvation.  See tokio-rs/tokio/pull/2160.
