### ISSUE TITLE
Could I do this in a cleaner way (async actor handling)?

### ISSUE THREAD

**Issue by Luminoth** [actix/actix#386]
Hi, I'm currently doing this to get async actors working:

```
#[derive(Message)]
#[rtype(result = "Result<(), ()>")]
pub struct CleanupMessage;

...

impl Handler<CleanupMessage> for CleanupActor {
    type Result = ResponseActFuture<Self, <CleanupMessage as Message>::Result>;

    fn handle(&mut self, _msg: CleanupMessage, _ctx: &mut Self::Context) -> Self::Result {
        if self.is_shutting_down() {
            return Box::pin(async {}.into_actor(self).map(|res, _act, _ctx| Ok(res)));
        }

        if self.cleanup_in_progress {
            return Box::pin(async {}.into_actor(self).map(|res, _act, _ctx| Ok(res)));
        }

        let now = Utc::now();
        if (now - self.last_cleanup).num_seconds() < self.cleanup_rate {
            return Box::pin(async {}.into_actor(self).map(|res, _act, _ctx| Ok(res)));
        }

        self.cleanup_in_progress = true;
        Box::pin({
            let config = self.config.clone();

            async move {
                CleanupActor::cleanup(config).await;
            }
            .into_actor(self)
            .map(|res, act, _ctx| {
                act.last_cleanup = now;
                act.cleanup_in_progress = false;

                Ok(res)
            })
        })
    }
}
```

The first thing is having to use a Result in the message, is that correct? If I used a result of just (), it would error out. The second is these bits:

```
        if self.is_shutting_down() {
            return Box::pin(async {}.into_actor(self).map(|res, _act, _ctx| Ok(res)));
        }
```

Is there something else that could be returned there to clean that up?

**Comment by robjtede** [comment]
I think you're looking for the helpers in the fut module: https://docs.rs/actix/0.9.0/actix/fut/index.html. You may be able to replace:

```rust
Box::pin(async {}.into_actor(self).map(|res, _act, _ctx| Ok(res)));
```

with:

```rust
fut::ok(());
```

**Comment by Luminoth** [comment]
Ahhh, sweet, yep that was it, although it did need wrapped in the Box::pin() as well, but that makes sense.

And on the other question - it is correct to have to use Result<(), ()> instead of just () for the Actor Result here?

**Comment by robjtede** [comment]
Depends on the semantics of the message. Do you need to signal success or failure of the action itself and handle each case as the message sender? Seems like you're not returning Err(...) anywhere in your example code so a () return type might be fine.

**Comment by Luminoth** [comment]
Huh, I must have had something else going on earlier because it wasn't letting me use (). Do those fut::ok()'s above then change to fut::ready(()) ?
