### ISSUE TITLE
run_in_tokio doesn't support stop on panic.

### ISSUE THREAD

**Issue by Future2100** [actix/actix#388]
I want to use actix_web with tokio runtime, Also, when somewhere panic, I want to exit the complete system.

**Comment by fMeow** [comment]
In an async runtime, you can spawn multiple `Future`. And panic only stop the corresponding `Future`. 

If you want to exit the system, use [`actix::System::current().stop()`](https://docs.rs/actix/0.10.0-alpha.3/actix/prelude/struct.System.html#method.stop) or [`tokio::runtime::Runtime::shutdown_timeout`](https://docs.rs/tokio/0.2.21/tokio/runtime/struct.Runtime.html#method.shutdown_timeout).

The nearest solution to your issue might be `stop_on_panic` option on actix runtime. The default `actix::System` set the `stop_on_panic` to `false`, and you might create a `System` to use this feature. Here is an example:

```rust
let sys = actix::System::builder().stop_on_panic(true).name("main").build();
sys.run();
```

**Comment by fakeshadow** [comment]
run_in_tokio is removed. Consider use `System::with_tokio_rt` for custom tokio runtime.
But mostly you want panic = abort in your Cargo.toml
