### ISSUE TITLE
Semantic issue labels for Actix Core

### ISSUE THREAD

**Issue by naturallymitchell** [actix/actix#396]
With [Semantic issue labels](https://github.com/patchworkuniversity/issue-labels), it would be easier to see good next steps forward. https://github.com/actix/actix-web/issues/1291

[Sane GitHub Labels](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63) explains this well

**Comment by JohnTitor** [comment]
Basic labels like actix-web are prepared now.
