### ISSUE TITLE
Diagram of Actix framework

### ISSUE THREAD

**Issue by naturallymitchell** [actix/actix#397]
A diagram of Actix and Actix Net for the handbook would really help to explain how network services built on top of it work.  Something like this diagram, for example:  

![](https://user-images.githubusercontent.com/27893/58935105-fd8d7700-879e-11e9-8e09-2334eef8aee1.png)

(diagram taken from [Rust Study 2019-06-05: actix-web 1.0 official release](https://github.com/RustStudy/rust_daily_news/blob/e2ba0e0660388cee0319f4329d6b20375f343af5/news/2019/06/05.md))

**Comment by shujaatak** [comment]
The [crude ascii pictoral form](https://github.com/actix/actix-web/issues/1521#issuecomment-631511428) shared by @robjtede is one step towards it but fairly complete **UML / Sequence diagram** will help new users / contributors a lot.

**Comment by robjtede** [comment]
We have some diagrams on the website:
- https://actix.rs/docs/http_server_init/
- https://actix.rs/docs/conn_lifecycle/
