### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix#4]

**Comment by mitchtbaum** [comment]
Please also show how to [model dependent tasks](https://www.reddit.com/r/scala/comments/4t2zmz/modeling_dependent_tasks_in_akka/), such as an example using [fork-join-executor](https://doc.akka.io/docs/akka/2.5/scala/dispatchers.html).

**Comment by mitchtbaum** [comment]
Perhaps a `chat-example-manager` could demo [model dependent tasks](https://www.reddit.com/r/scala/comments/4t2zmz/modeling_dependent_tasks_in_akka/), eg. (1) launch with some preconfigured settings, (2) reset it by constructing an execution graph that first sends messages to each user, then disconnects them, then archives the logs for each room, and (3) respawn the rooms.

I believe Akka does this with [fork-join-executor](https://doc.akka.io/docs/akka/2.5/scala/dispatchers.html), or much more interestingly with [stream graphs](https://doc.akka.io/docs/akka/2.5.3/scala/stream/stream-graphs.html) which might leverage libraries such as, [petgraph](https://github.com/bluss/petgraph) and [futures-state-stream](https://github.com/sfackler/futures-state-stream).

**Comment by fafhrd91** [comment]
as I understand Akka runs each actor in separate thread, here is example if you really want worker style actors with work-steal queue for messaging https://fafhrd91.github.io/actix/actix/sync/index.html

I am not sure about streams. it is built on top of futures-rs, if you want to work with streams you can just use [Streams](https://docs.rs/futures/0.1.16/futures/stream/trait.Stream.html)
