### ISSUE TITLE
Can we add std::marker::Sync for Recipient type?

### ISSUE THREAD

**Issue by fakeshadow** [actix/actix#401]
### Benefit: 
By adding `Sync` to `Sender` trait object we can make `Recipient` a type that is `Send` + `Sync` which can be wrapped in thread safe smart pointers like `Arc<RwLock<Recipient<CertianMessage>>>`.

### Changes to code:
```
pub struct Recipient<M: Message>
where
    M: Message + Send,
    M::Result: Send,
{
    tx: Box<dyn Sender<M> + Sync>,
}

pub trait Sender<M>: Send
where
    M::Result: Send,
    M: Message + Send,
{
    fn boxed(&self) -> Box<dyn Sender<M> + Sync>;
}

```
With some related methods to match the same signature

### Safety:
From what I see we only boxed `AddressSender`  type with `Sender` trait which seems to be a `Send` + `Sync` type. 
That being said I could be wrong about this so please let me know if I get something wrong about this whole idea.

**Comment by JohnTitor** [comment]
I think this can be closed by #403.
