### ISSUE TITLE
Implement `Send` for `actix::message::Request` explicitly

### ISSUE THREAD

**Issue by ffuugoo** [actix/actix#405]
## Expected Behavior
`actix::message::Request` explicitly (and unconditionally) implements `Send` regardless if it's `A` type-argument implements `Send`.

## Current Behavior

- `Request` contains `PhantomData<A>`
- `PhantomData<T>: Send` only when `T: Send`
- so, as a result, `Request` only implements `Send`, when it's `A` type-argument implements `Send`

As far as I can see, there is no real reason for that. `Request` does not ever directly interact with actor, only sends a message through a channel.

## Possible Solution

I've looked through the code, this seems to be enough:

```rust
unsafe impl<A, M> Send for Request<A, M> 
where
    A: Handler<M>,
    A::Context: ToEnvelope<A, M>,
    M: Message + Send,
    M::Result: Send,
{
}
```

## Context

I'm working on a web-service using `actix-web` and `juniper` (GraphQL implementation in Rust). Due to current shortcomings in `juniper` it requires `Send` futures. So, if I want to interact with my actors from inside my GraphQL handlers, I have to heavily bound all my actors to be `Send`.

## Your Environment

- Rust Version: 1.44.1
- Actix Version: 0.9, 0.10-*

**Comment by tyranron** [comment]
@ffuugoo there is no sense to provide `unsafe impl Send`. It's enough to use `PhantomData<std::thread::JoinHandle<T>>` instead of just `PhantomData<T>`. Better go with a PR.

**Comment by ffuugoo** [comment]
@tyranron Opened #407, only made it `AtomicPtr` rather than `JoinHandle`, cause it seems better fitting (kinda like `*const A`).

**Comment by tyranron** [comment]
@ffuugoo you've did even better droping the redudant `PhantomData` 👍
