### ISSUE TITLE
current_thread documentation

### ISSUE THREAD

**Issue by shutton** [actix/actix#416]
The documentation currently indicates (in `src/lib.rs`):

```
//! At the moment actix uses
//! [`current_thread`](https://docs.rs/tokio/0.1.13/tokio/runtime/current_thread/index.html) runtime.
//!
//! While it provides minimum overhead, it has its own limits:
//!
//! - You cannot use tokio's async file I/O, as it relies on blocking calls that are not available
//! in `current_thread`
//! - `Stdin`, `Stderr` and `Stdout` from `tokio::io` are the same as file I/O in that regard and
//! cannot be used in asynchronous manner in actix.
```

However, it appears that `current_thread` was deprecated in tokio 0.2, so this likely needs a bit of a tweak (assuming it still applies).

**Comment by fakeshadow** [comment]
A recent search only find `current_thread` in migration guide.
So I believe what related are removed or updated.

**Comment by robjtede** [comment]
I removed that recently after realising it was no longer relevant. Forgot about this issue.
