### ISSUE TITLE
Naming Result vs Response

### ISSUE THREAD

**Issue by martinitus** [actix/actix#417]
Hi folks,

Im pretty new to rust and its Result/Option core structs. Thats why the following line just confused me a lot.

https://github.com/actix/actix/blob/6b5bba584cf4f812707cbac54cb44af3c9d908ad/src/handler.rs#L29

As I understood the `Response` may be a `Result` but still, why not simply stick with `Response` to keep consistence ;-)

I think a simply _refactor rename "Result" to "Response"_ in this and the `Message` trait would reduce the amount of caused headache, maybe also for other newbees like me ;-)

It also makes many of the other traits defined in the file read more understandable. I understand, that changing a name at the core of the thing isnt that easy thou :-(

Anyway! Awesome library!! ;-)

HtH Martin 

PS: the initial cause of confusion ;-)
https://github.com/actix/actix/blob/6b5bba584cf4f812707cbac54cb44af3c9d908ad/src/handler.rs#L305

**Comment by fakeshadow** [comment]
`Handler::Result` is an associate type and you should know the difference of it from actual types.
There is `handler::Response` type and use it as associate type would also brings up confusion for you.
