### ISSUE TITLE
add function to run task every x seconds

### ISSUE THREAD

**Issue by Anton-4** [actix/actix#42]
For my use case it would be very useful to be able to run a task every x seconds,
so just like `run_later` for `AsyncContext` but instead of running once, it would repeat
every time the duration has passed.

Thank you for this useful framework!

**Comment by fafhrd91** [comment]
it is trivial to implement, is it worth to add this? new method will increase size of the api. which is large already

**Comment by Anton-4** [comment]
It seems like something that would be often useful in the context of actor systems.
It's trivial to implement but I feel like it's cleaner if it's in the API.
Akka also has a similar method in the [API](https://doc.akka.io/docs/akka/2.5/scheduler.html).

**Comment by fafhrd91** [comment]
Would you provide PR?

**Comment by Anton-4** [comment]
Yeah sure :)
