### ISSUE TITLE
Tokio Reform and Actor Execution

### ISSUE THREAD

**Issue by proman21** [actix/actix#43]
If you are unaware, the tokio project [just pushed tokio 0.1](https://tokio.rs/blog/2018-02-tokio-reform-shipped/) which is a major reform of the scope of tokio. In relation to this project, this significantly changes actor scheduling and dispatching.

The first immediate concern is that actix can no longer use the tokio event loop as a executor; however I see this a wonderful opportunity to **rewrite the entire actor execution stack to provide more varied methods of running an actor system**.

One of the bigger paper-cuts of this library is the inflexibility of the current `System`/`Arbiter` methodology. You **HAVE** to run the `System` before you can use `Arbiter`'s to manage other threads. Although you can run the system in another thread to begin with, it requires you to perform that thread management by yourself, which might be too much for a simple project.

I would love to see the ability to request actors be run on specific executors that can provide guarantees that suit the actors workload. Things like pinned thread pools, fork-join pools and single-threaded executors. This would broaden the set of applications Actix can work for and give more flexibility to developers to get the best performance out of their system. We can then also build test harnesses for actor systems and even start providing different mailbox types and supervised actor routing.

In either case, we are going to have to evolve because of this change. But it is a great diving board from which to make these changes.

**Comment by fafhrd91** [comment]
I don't think tokio reform changes much. actix doesn't use executors api. it uses reactor, and it is still in-place. 

regarding different types of execution context, I am not sure you can unify actor executors subsystem. i.e. actor type is tightly coupled to it's context, developer decides which context to use for specific actor. you can't just use async actor within thread pool context. maybe it is possible to unify execution contexts for sync actors specifically, but i don't have enough use cases to make generalization. just in case, you can create [worker style actors with work stealing queue in front](https://github.com/actix/actix/blob/master/src/sync.rs)

I am not sure about System/Arbiter inflexibility, could you elaborate and maybe provide a way how would you modify it.

in general, I build actix api as requirements for my use cases. but I am open for any changes.

**Comment by proman21** [comment]
The `Reactor` doesn't work the way it used to. Before it performed both I/O readiness notifications and could executer arbitrary futures. Now it's a global, implicit, I/O only event thread. The execution behavior is a [calling thread executor](https://docs.rs/tokio/0.1.0/tokio/executor/current_thread/index.html) separate from the I/O system. This does change at least the code used to create the system actor or arbiters.

Current actix supports two types of execution.

1. A single-threaded, cooperative executor that executes all actors on the same thread. This is `System`/`Arbiter`
2. A thread pool executor that pins an actor to a thread, and only executes that actor, with the possibility to spin up more threads with a new actor instance. This is the `SyncArbiter` that you linked me.

The issue is that executor 1. only allows for one-at-a-time actor execution; parallelism is significantly reduced if actors have to wait for others to finish. Executor 2. does allow for bulk-heading, but it's limited to one kind of actor per thread pool.
Additionally, each actor doesn't get to chose a executor, it is limited by which trait it implements, and which arbiter it is started on.

It would be useful to include a work-stealing thread pool that is agnostic to what actors it executes, and can provide parallelism of actor execution. This also comes with the proposal to change how actors are scheduled to execute. An actor should be able to specify that it is run on a specific kind of executor, a pinned thread pool because it performs blocking work, or the work-stealing thread pool because it wants to run in parallel.

The single-threaded executor is still great for small-ish systems that don't need parallelism or won't block on external events, and it works great for testing a system because it is easier to reason about.

**Comment by fafhrd91** [comment]
regarding actor context:

1. You can always start multiple Arbiters and use SyncAddress for actor communication. Developer needs to make explicit decision about topology of the actors, but that is easy. I think this is common for async applications. for example actix-web uses multiple threads and one io accept thread and it perform very well.

2. correct me if I am wrong, you want to run multiple actors in same set of threads? I actually like this idea.

regarding reactor. I don't see big difference, instead of Core you use TaskExecutor and spawn futures on it. yes, api is different but you still can submit futures to executor and futures can wait on IO events

**Comment by fafhrd91** [comment]
right now I am very busy with actix-web project. 

Do you want to work on any actix features?

**Comment by proman21** [comment]
TaskExecutor can't spawn futures onto the `current_thread` executor after the closure passed to `current_thread::run` has been called, because the thread is blocked executing the futures. So either you specify all futures needed to run in that closure, or you use channels and `UnorderedFutures` to allow futures to be submitted to a root Future. This is based on my read-through of the source.

You can always start multiple arbiters, but you need to start the System one first, which is an issue if your building an actor system with a library facade over it. The System always uses the current calling thread, which is not always ideal.

Yes, basically a thread pool where each thread has a work-stealing queue of actors/futures to run. If a thread has finished work, it can steal actors from another threads queue. Good for parallelism, bad if you need thread-affinity to improve performance.

I'm working on my own projects for now but I already started looking at these ideas in my own fork. So I plan on dropping some PR's for new features later.

**Comment by fafhrd91** [comment]
System is useful as a singleton, for example you can handle unix signals only in one thread, so you can always use System as house keeping thread. Usually libraries should not start System. System is application concern.

I like idea of work stealing executor, but it can not be only sync executor, because of ```Sync+Send``` requirements. SyncArbiter requires Sync+Send only for actor factory.

**Comment by fafhrd91** [comment]
as a side note, 

i built actix library as a way to simplify async programing (if you check early commits, there was no actors). it evolves based on my use cases, that is the reason why it looks like it look.

**Comment by fafhrd91** [comment]
@proman21 btw do you have any actionables for this ticket?

i dont like when tickets hangs for long time without obvious actionable

**Comment by proman21** [comment]
The only mandatory action is to **Update `tokio-core` library to `tokio 0.1`**. This will require a change to how Arbiter is implemented. Other actions might be

- Plan and design different dispatchers, like fork-join pool, pinned thread, etc.
- Plan for API that exposes these different dispatchers to Actor impl's.

**Comment by fafhrd91** [comment]
actix is migrated to tokio
