### ISSUE TITLE
Update `tokio` to 1.0

### ISSUE THREAD

**Issue by incker** [actix/actix#437]
New version of tokio is released
tgbot vesrion of tokio is 0.2 [Cargo.toml](https://github.com/actix/actix/blob/master/Cargo.toml)

Better upgrade, to avoid downloading two versions of tokio in projects

**Comment by JohnTitor** [comment]
I'm happy to do it but let me take a look at the upstream dependencies.

**Comment by fakeshadow** [comment]
The main blocker seems to be actix-server which is still using mio 0.6.
The latest version has some serious breaking change with some features gonna so some big changes and extra deps could be needed.

**Comment by sazzer** [comment]
Just hit this as a problem when I updated `deadpool` and `tokio-postgres` from 0.5 to 0.6, which now depends on tokio 0.3 instead. As soon as I did that, all my database stuff stopped working because of the mismatch in versions :(

Easily fixed locally by just *not* updating, but would be nice to be able to keep everything up to date.

**Comment by robjtede** [comment]
For that, you may have success with the compat layer for 2-3 migration.

**Comment by fakeshadow** [comment]
Would suggest remain on tokio 0.2 for the time being. There is no clear timeline for the blocking upstream deps that are still on tokio 0.2.

**Comment by nazar-pc** [comment]
Same with `redis` crate, new version with important fixes was released a few days ago, but they also switched to Tokio 0.3 at the same time.
Those who need 0.2 can use older version of Actix, but it would be easier with upgrades to move to 0.3 as soon as possible.

Compat only works the other way around, running 0.2 code on 0.3, but Actix itself uses 0.2 internally.

**Comment by fakeshadow** [comment]
There is no much actix-web can do when upstream deps are still stick with tokio 0.2.

Adding the fact that tokio 0.3 is considered a beta for the upcoming tokio 1.0. There is really not much improvement for now from 0.2 and you would soon rush to tokio 1.0 again. For a project like actix-web it's not a good idea to rush for every new release.

If some of crate uses moves on early and push critical fixes exclusively for tokio 0.3. It's better to ask them the possibility of a backport for the time being.

**Comment by vmasdani** [comment]
just a heads up... tokio 1.0  just came out today

**Comment by robjtede** [comment]
#443

**Comment by lucab** [comment]
@robjtede @JohnTitor it would be helpful to have a final 0.11.0 version tagged which includes this tokio bump, as it would unblock dependencies updates in consumers.
