### ISSUE TITLE
async handlers with responses

### ISSUE THREAD

**Issue by mankinskin** [actix/actix#438]
Are there any plans for adding something like an `AsyncHandler` trait:
```rust
pub trait AsyncHandler<M> 
where
    Self: Actor,
    M: Message, 
{
    type Result: MessageResponse<Self, M>;
    async fn handle(&mut self, msg: M, ctx: &mut Self::Context) -> Self::Result;
}
```
which can return a future and has internally managed async memory access?

I would really like to use actix with async APIs. I can use it with [actix-interop](https://github.com/Diggsey/actix-interop) right now, but that introduces a lot of boilerplate, especially because it requires the state used by the async code to be completely `'static`, which means I have to manage all of my actor's state (that should be accessed by async functions) in a `lazy_static` variable. It would be nice if this could be handled by actix and if I could just write async code directly in an actix handler, which can also return responses.

**Comment by fakeshadow** [comment]
Rust doesn't support async methods in trait so what you write is wrong in syntex.

That said It's likey that you are talking about using macros like `asynct_trait` but there are downsides:

1. It's desugar to `Pin<Box<dyn Future>>` which means you get what we have now in the end. It's an illusion that you are writing async trait method. It sure is useful but is it worth it to complicate the code with such illusion?

2. The macro would have to figure a way to put part of your handle method in async block as you can't borrow self in an async block. It's the design of actix and how an actix actor can poll multiple messages concurrently. This result in either like `actix-interop` using static and locks to aviod the lifetime issue and mutable borrow issue. Or the macro would do a very complex logic to figure out which part of your handle method can be put into an async block before throwing an error if it can not.  

What you actually want is an actor patter rather than actix. You want an actor that handle message one by one in async manner. It can borrow itself in async method and all other messages are held for later until the future is finished.

**Comment by mankinskin** [comment]
> 1. It's desugar to `Pin<Box<dyn Future>>` which means you get what we have now in the end. It's an illusion that you are writing async trait method. It sure is useful but is it worth it to complicate the code with such illusion?

If by illusion you mean syntax sugar, then that would make it less complicated wouldn't it? It would be much more convenient not to have to worry about boxing and pinning the future manually.

> What you actually want is an actor patter rather than actix

I thought actix implements an actor pattern.. I was thinking actix can store the actor's state in a static variable and execute the async handler functions in a tokio executor and handle all of the messaging and memory access internally.

I have no experience with actix's internal code base.. but this should be possible in theory right? Actors could be stored statically and the async handler could be wrapped in integration code managing the ugly integration code.

**Comment by fakeshadow** [comment]
With every extra trait the type signature of the code would be more complicated.
Let's say if we add this trait would we make user impl both or separately? Consider this trait for example.
```
pub trait ToEnvelope<A, M: Message>
where
    A: Actor + Handler<M>, 
    A::Context: ToEnvelope<A, M>,
{
    fn pack(msg: M, tx: Option<Sender<M::Result>>) -> Envelope<A>;
}
```
We either have make another similar trait for asyn handler, make another generic over handler type, or force user to impl both of the handler trait.

You can't do this in tokio either. For example:
```rust
let a = 32;
tokio::spawn(async move { println!("{}", &mut a) });
tokio::spawn(async move { println!("{}", &a) });
```

actix is an actor pattern but it's not what you imagine it be.

**Comment by mankinskin** [comment]
> Nothing stop you to store a smart pointer in actor state too. Like `Rc` and `Arc` would all work when you try to borrow the state with static lifetime.

Yes and this is exactly what I would like to have automated. async code can be very complicated to get right so it would be extremely useful to automate it at the lowest possible level.



> We have make another similar trait for asyn handler, or make another generic over handler type, or force user to impl both of the handler trait.

Yes, I am guessing an `async` handler would work fundamentally differently than a "sync" handler. It's state must have a static lifetime and it's handlers must return `Future`s. But that would be fine because they also behave differently, so this is more like an extension of the API than an enhancement.

The async API would handle all of what this code adds to your above example:
```
use async_std::sync::Mutex;
lazy_static! {
    static ref a: Arc<Mutex<u32>> = Arc::new(Mutex::new(32));
}

tokio::spawn(async move { println!("{}", &mut a.clone().lock().await) });
tokio::spawn(async move { println!("{}", &a.clone().lock().await) });
```

**Comment by fakeshadow** [comment]
There is several issue with your example:

1. static will live as long as your app. Lots of people use actor in shorter lifespan. for example `actix-web-actor` which is the websocket crate for `actix-web`. Using statics means you are leaking memeory with every disconnected websocket session as actor in that crate only lives as long as one client connection.

2. `Arc` and `Mutex` have cost and it's not everyone want. They can slow down your app and if you mean autoamted by force everyone to pay for that then it's really a bad idea.

3. actix actor runs on single thread so `Arc` and `Mutex` are overkill.

Consider this example instead. It achieves what you want with reasonable amount of code without breaking changes and without forcing everyone to use static and heavy smart pointers.

```rust
use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use actix::prelude::*;

struct A(Rc<RefCell<usize>>);

impl Actor for A {
    type Context = Context<Self>;
}


struct Msg;

impl Message for Msg {
    type Result = ();
}

impl Handler<Msg> for A {
    type Result = ();

    fn handle(&mut self, _: Msg, ctx: &mut Self::Context) -> Self::Result {
        let a = self.0.clone();
        async move {
            let mut borrowed = a.borrow_mut();
            actix_rt::time::delay_for(Duration::from_secs(1)).await;
            *borrowed += 1;
        }.into_actor(self).wait(ctx)
    }
}

#[actix_rt::main]
async fn main() {
    let a = A(Rc::new(RefCell::new(1)));
    let addr = a.start();

    addr.send(Msg).await.unwrap();
    addr.send(Msg).await.unwrap();

    System::current().stop();
}
```

**Comment by mankinskin** [comment]
> 1. static will live as long as your app

You can use dynamic datastructures like `Option` or `HashMap` to deallocate actors.



> 2\. `Arc` and `Mutex` have cost and it's not everyone want. They can slow down your app and if you mean autoamted by force everyone to pay for that then it's really a bad idea.

We don't have to implement it for every actor. I am talking about a separate type of actor, one that supports `async`, next to the current actor types. It would be completely optional.

> 3\. actix actor runs on single thread so `Arc` and `Mutex` are overkill.

As I have understood, this is not supposed to stay like this is it?

**Comment by mankinskin** [comment]
Maybe this ought to be an extension of the `SyncArbiter`? https://actix.rs/book/actix/sec-6-sync-arbiter.html

**Comment by fakeshadow** [comment]
Then it come back to the previous point. It would complicate the code by feature flags, duplicated traits or extrat type signature in user code. Little is gain tough.

**Comment by fakeshadow** [comment]
Just to be clear I like async handler too and I even wrote my own actor pattern just for that by copying the actix design.

It's just that it's hard to mix different design well and remain simple and consistent.

**Comment by mankinskin** [comment]
Yes you are right about that. And I wont try to hack something together that won't be usable in the end. Your input was very helpful, I will see if I will start working on a pull request in the future. There are some other actor frameworks around, maybe I can find what I need there. Then again, actix-web is a great plus, and without it I would have to integrate with something like tide, which requires work. The question is which is easier to do. Actix seems like a mature project, but I think it will definitely have to embrace async/await to be able to keep up. async/await was stabalized after actix was already far in development, I guess that is why it never got built in. But I maybe we can start adding it soon.

**Comment by fakeshadow** [comment]
You can use async/await easily in actix though.

There is simply no way to write async method in traits until GAT stables and you are just chasing an illusion of writing it when at last you always get a boxed trait object. 
Until that happen there is no actual gain to switch. Actix has long exists before async/await and it's not like we can add a macro and magically make it work. It would break a lot of working code. For not changing anything.

I doubt you can get anything work either. I'm not questioning your design or skill. It's just there is almost no way to keep the ability of concurrent message processing with every async task borrow the state mutablely. No amount of lock and static var will save you from that. You always end up halt other message and/or block the arbiter as long as you hold the lock.

**Comment by mankinskin** [comment]
I mean it is working with `actix_interop`, and it is not too much boilerplate. But if it works with that crate, I don't understand why it wouldn't work with actix directly. of course the future will be boxed, the state will need to be static and locked, but there is certainly a benefit of removing the boilerplate related to that. Currently, I have to write actors using async functions like this (I think):
First, I implement the static state. For this I need a separate struct from the one I use for the actor, because the actor should not be static, but should only access the static state through a lock
```rust
lazy_static! {
    static ref SUBSCRIPTIONS: Arc<RwLock<StaticSubscriptions>> = Arc::new(RwLock::new(StaticSubscriptions::default()));
    static ref SUBSCRIPTION_IDS: AtomicUsize = AtomicUsize::new(0);
}
// read the static state
pub async fn subscriptions() -> RwLockReadGuard<'static, StaticSubscriptions> {
    SUBSCRIPTIONS.read().await
}
// mutate the static state
pub async fn subscriptions_mut() -> RwLockWriteGuard<'static, StaticSubscriptions> {
    SUBSCRIPTIONS.write().await
}
// stores the payload
#[derive(Default)]
pub struct StaticSubscriptions {
    pub subscriptions: HashMap<usize, Arc<RwLock<SubscriptionCache>>>,
    new_subscriptions: bool,
}
// implements business logic
impl StaticSubscriptions {
    fn new_subscription_id() -> usize {
        SUBSCRIPTION_IDS.fetch_add(1, Ordering::Relaxed)
    }
    pub async fn add_subscription(&mut self, request: PriceHistoryRequest) -> Result<usize, Error> {
        debug!("Adding subscription...");
        if let Some((id, _)) = self.find_subscription(request.clone()).await {
            debug!("Model already exists.");
            Ok(id)
        } else {
            let id = Self::new_subscription_id();
            self.subscriptions.insert(id.clone(), Arc::new(RwLock::new(SubscriptionCache::from(request))));
            self.new_subscriptions = true;
            Ok(id)
        }
    }
    pub async fn find_subscription<'a>(
        &'a self,
        request: PriceHistoryRequest,
    ) -> Option<(usize, Arc<RwLock<SubscriptionCache>>)> {
        let req = Arc::new(request);
        futures::stream::iter(self.subscriptions.iter())
            .then(move |(id, cache)| {
                let req = req.clone(); 
                async move {
                    if cache.read().await.subscription == req.as_ref() {
                        Some((id.clone(), cache.clone()))
                    } else {
                        None
                    }
                }
            })
            .collect::<Vec<_>>()
            .await
            .into_iter()
            .find_map(|opt| opt)
    }
    pub async fn get_subscription<'a>(
        &'a self,
        id: usize,
    ) -> Result<Arc<RwLock<SubscriptionCache>>, crate::Error> {
        self.subscriptions
            .get(&id)
            .map(Clone::clone)
            .ok_or(crate::Error::from(Error::from(format!(
                "No Subscription with ID: {}",
                id
            ))))
    }
    pub async fn get_subscription_list(&self) -> Result<HashMap<usize, PriceSubscription>, crate::Error> {
        Ok(futures::stream::iter(self.subscriptions.iter())
            .then(async move |(id, cache)| (id.clone(), cache.read().await.subscription.clone()))
            .collect()
            .await)
    }
}
```
Then I implement the actor, which will be created and polled by actix, create futures, which get executed by tokio and access the locked, static state asynchronously:
```rust
pub struct Subscriptions;
// implements the API to use this actor
impl Subscriptions {
    pub async fn init() -> Addr<Self> {
        Self::create(move |_| Self)
    }
    pub async fn add_subscription(req: PriceHistoryRequest) -> Result<usize, Error> {
        subscriptions_mut()
            .await
            .add_subscription(req)
            .await
    }
    pub async fn find_subscription(request: PriceHistoryRequest) -> Option<(usize, Arc<RwLock<SubscriptionCache>>)> {
        subscriptions()
            .await
            .find_subscription(request)
            .await
            .clone()
    }
    pub async fn get_subscription(id: usize) -> Result<Arc<RwLock<SubscriptionCache>>, crate::Error> {
        subscriptions()
            .await
            .get_subscription(id)
            .await
            .clone()
    }
    pub async fn get_subscription_list() -> Result<HashMap<usize, PriceSubscription>, crate::Error> {
        crate::subscriptions()
            .await
            .get_subscription_list()
            .await
    }
}

// actix stuff starts here
impl Actor for Subscriptions {
    type Context = Context<Self>;
}
// creates futures to handle the incoming ClientMessages and return responses to actix using actix_interop
impl Handler<ClientMessage> for Subscriptions {
    type Result = ResponseActFuture<Self, Option<ServerMessage>>;
    fn handle(
        &mut self,
        msg: ClientMessage,
        _: &mut Self::Context,
    ) -> Self::Result {
        async move {
            match msg {
                ClientMessage::AddPriceSubscription(request) => {
                    info!("Subscribing to market pair {}", &request.market_pair);
                    let id = Self::add_subscription(request.clone()).await.unwrap();
                    Some(ServerMessage::SubscriptionAdded(id))
                },
                ClientMessage::GetPriceSubscriptionList => {
                    info!("Getting subscription list");
                    let list = Self::get_subscription_list().await.unwrap();
                    Some(ServerMessage::SubscriptionList(list))
                },
                _ => None,
            }
        }.interop_actor_boxed(self)
    }
}
```

And this could probably be automatically implemented by something like:
```rust
lazy_static! {
    // unrelated to actix
    static ref SUBSCRIPTION_IDS: AtomicUsize = AtomicUsize::new(0);
}
// stores the payload
#[derive(Default)]
pub struct Subscriptions {
    pub subscriptions: HashMap<usize, Arc<RwLock<SubscriptionCache>>>,
    new_subscriptions: bool,
}
// implements business logic
impl Subscriptions {
    pub async fn init() -> Addr<Self> {
        Self::create(move |_| Self::default())
    }
    fn new_subscription_id() -> usize {
        SUBSCRIPTION_IDS.fetch_add(1, Ordering::Relaxed)
    }
    pub async fn add_subscription(&mut self, request: PriceHistoryRequest) -> Result<usize, Error> {
        debug!("Adding subscription...");
        if let Some((id, _)) = self.find_subscription(request.clone()).await {
            debug!("Model already exists.");
            Ok(id)
        } else {
            let id = Self::new_subscription_id();
            self.subscriptions.insert(id.clone(), Arc::new(RwLock::new(SubscriptionCache::from(request))));
            self.new_subscriptions = true;
            Ok(id)
        }
    }
    // ... remaining implementations
}

// actix stuff starts here
impl AsyncActor for Subscriptions {
    type Context = AsyncContext<Self>;
}
// creates futures to handle the incoming ClientMessages and return async responses to actix
impl AsyncHandler<ClientMessage> for Subscriptions {
    type Result = Option<ServerMessage>;
    async fn handle(
        &mut self,
        msg: ClientMessage,
        _: &mut Self::Context,
    ) -> Self::Result {
        match msg {
            ClientMessage::AddPriceSubscription(request) => {
                info!("Subscribing to market pair {}", &request.market_pair);
                let id = Self::add_subscription(request.clone()).await.unwrap();
                Some(ServerMessage::SubscriptionAdded(id))
            },
            ClientMessage::GetPriceSubscriptionList => {
                info!("Getting subscription list");
                let list = Self::get_subscription_list().await.unwrap();
                Some(ServerMessage::SubscriptionList(list))
            },
            _ => None,
        }
    }
}
```
right? And that would definitely be an improvement to the API.

**Comment by fakeshadow** [comment]
Am I not clear enough? I'm not saying it's not working. It's you would lose CONCURRENCY.

You example would result in an actor handle only message at a time. You actor would stuck on a future as long as it holds the lock.

**Comment by mankinskin** [comment]
> You example would result in an actor handle only message at a time. You actor would stuck on a future as long as it holds the write lock.

Yes obviously. There is no way around that, if the state is static. Only one handler can write the static state at a time.

But you are right, it would be better to split messages into reads and writes, so maybe we need an `AsyncWriteHandler` and an `AsyncReadHandler`, which take `&mut self` and `&self` respectively.

Then to avoid locking too much state, the user can put each part of the state behind an `Arc<RwLock<_>>` and work on that in an `AsyncReadHandler` (as I did for each item in `SUBSCRIPTIONS`, the `SubscriptionCache`s).

Then the `AsyncReadHandler` can spawn a new task for the part it should work on (`Arc<RwLock<SubscriptionCache>>`), return to the runtime, and only the relevant part is locked. 

I am just looking for ways to make this more ergonomic, while staying correct. If that is possible, then why not do it? It would be worth it.

**Comment by fakeshadow** [comment]
My inplementation. No locks. No statics. 
https://github.com/fakeshadow/actix-async.

**Comment by mankinskin** [comment]
@fakeshadow Great work!

**Comment by bergkvist** [comment]
Can your implementation be used with websockets @fakeshadow ?

I'm currently struggling with the following:
```rust
impl Actor for MyWebSocket {
    type Context = ws::WebsocketContext<Self>;
    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.run_interval(HEARTBEAT_INTERVAL, |act, ctx| {
            if Instant::now().duration_since(act.heartbeat) > CLIENT_TIMEOUT {
                println!("Websocket Client heartbeat failed, disconnecting!");
                ctx.stop();
                return;
            }
            ctx.ping(b"");
        });
        // tokio::sync::watch::Reciever
        let mut rx = self.topic.receiver.clone();
        let future = async move {
            while rx.changed().await.is_ok() {
                println!("sending = {:?}", *rx.borrow());
                ctx.text(rx.borrow().to_string());
            }
/*`ctx` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
...is used here...rustcE0759
main.rs(74, 32): this data with an anonymous lifetime `'_`...
main.rs(90, 38): ...and is required to live as long as `'static` here
actor.rs(288, 50): `'static` lifetime requirement introduced by this bound*/
        };
        self.spawn_handle = Some(ctx.spawn(future.into_actor(self)));
    }
    fn stopped(&mut self, ctx: &mut Self::Context) {
        if let Some(handle) = &self.spawn_handle {
            ctx.cancel_future(*handle);
            self.spawn_handle = None;
        }
    }
}
```

**Comment by wry0313** [comment]
I have a chat app that uses actix and have async operations (talking to db) in the message handler and it is working great: https://github.com/wry0313/renu-marketplace/blob/main/src/websocket/server.rs

**Comment by arielscarpinelli** [comment]
Just started working on a macro to support this https://github.com/concurrentes-fiuba/actix-async-handler

**Comment by Sytten** [comment]
Looks good @arielscarpinelli , I will give it a shot. I would improve your readme a bit.
Do you want to contribute it to this repo?

One thing I like about actix vs other actor frameworks is the possibility to have non atomic/concurrent processing of messages.

**Comment by arielscarpinelli** [comment]
I think this repo is in maintenance only, I don't know if they would take such contribution. Also until we fix https://github.com/concurrentes-fiuba/actix-async-handler/issues/1 I don't think it can be considered initially ready. But shouldn't need mucho more to get there.

Readme certainly needs love. Contributions are welcome!

**Comment by Sytten** [comment]
I can merge in this repository, so it is fine.

Agreed it needs some battle testing. I am wondering if you could take a page from the rust compiler code for async/await since they essentially desugar that code to a state machine which is a similar problem.

**Comment by arielscarpinelli** [comment]
Actually my first inspiration was the original async attribute macro from before it was part of the compiler https://github.com/alexcrichton/futures-await/blob/master/futures-await-async-macro/src/lib.rs
