### ISSUE TITLE
Remove resolver actor from actix

### ISSUE THREAD

**Issue by fakeshadow** [actix/actix#451]
## Expected Behavior
actix as an actor framework should not be bind to a dns dependency.
I believe majority people don't use that feature or they would be fine to move that feature to user code base.

## Current Behavior
actix was blocked from update to tokio 1.0 because the said dep is still not ready.
At this point actix is unblocked but the point still stands.

## Possible Solution
Remove the feature.

**Comment by Chaostheorie** [comment]
Would love to take a crack at it, if this issue isn't stale or superseded (@fakeshadow ?).

**Comment by fakeshadow** [comment]
> 
> 
> Would love to take a crack at it, if this issue isn't stale or superseded (@fakeshadow ?).

An related PR was made to deprecate the feature. 

PR is welcome to actually remove it since there is no opposing response for doing so.

**Comment by Chaostheorie** [comment]
Okay. I'm going to attempt to create the changes with a related PR this weekend. Would it be desired to have the functionality still in a separate crate or is the whole feature already deprecated?

**Comment by robjtede** [comment]
if anyone still needs it they can rip the code from the old versions

**Comment by Chaostheorie** [comment]
kay
