### ISSUE TITLE
`SinkWrite::write` should return `Result<(), I>` instead of `Option<I>`

### ISSUE THREAD

**Issue by idanarye** [actix/actix#498]
In version 0.9 and below [`SinkWrite::write`](https://docs.rs/actix/0.9.0/actix/io/struct.SinkWrite.html#method.write) would return a `Result`, but [in 0.10 it changed to return an `Option`](https://docs.rs/actix/0.10.0/actix/io/struct.SinkWrite.html#method.write) - I assume in order to return the unsent value?

Using `Option::None` as a success value is confusing - the idiomatic success value is `Ok`, and the idiomatic error value is `Err`. The fact that 0.10 had to document the meaning of the return value where in 0.9 it was obvious is a testimony to that. `Result<(), I>` is also returning the unsent item in case of failure, and is much less confusing.

**Comment by robjtede** [comment]
makes sense, PR welcome
