### ISSUE TITLE
Configurable stacksize for threads started via SyncArbiter

### ISSUE THREAD

**Issue by let4be** [actix/actix#508]
I'd like to configure stack size(and probably give threads names), afaik it's currently not possible.

**Comment by nickx720** [comment]
Hi, I'd like to take this ticket. I would need some help. @robjtede. If my understand the ask correctly for configuring the stack size, would extending the struct SyncAribter for threads field suffice?
`pub struct SyncArbiter<A>
where
    A: Actor<Context = SyncContext<A>>,
{
    queue: Option<cb_channel::Sender<Envelope<A>>>,
    msgs: AddressReceiver<A>, 
    threads:usize
}
`
And adding a corresponding set_stack_size method on the impl?

**Comment by naturallymitchell** [comment]
@nickx720 have you tried asking on Discord?

**Comment by kevincox** [comment]
I'm hitting this issue on debug builds which makes development incredibly painful as I need to do a release build which takes many minutes.
