### ISSUE TITLE
Examples for websocket in https://github.com/actix/examples/tree/master/websockets/websocket have an compile error when actix's version is more than 0.10.0

### ISSUE THREAD

**Issue by cv1002** [actix/actix#511]
## Expected Behavior

The codes below should compiled, and run.
```Rust
use actix::prelude::*;
use actix_web_actors::ws;
struct MyWebSocket {
}

impl Actor for MyWebSocket {
    type Context = ws::WebsocketContext<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
    }
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    Ok(())
}

```

## Current Behavior

I get a compile error says "the trait bound `MyWebSocket: actix::actor::Actor` is not satisfied" when the version of actix more than 0.10.0(but 0.10.0 compiles!).
It's confusing! The codes is copied from https://github.com/actix/examples/tree/master/websockets/websocket.

## Possible Solution

I don't know how to solve the error, but actix version 0.10.0 doesn't have this error.

## Steps to Reproduce (for bugs)

1. Copy the codes
2. Add dependencies configuration(use actix = "0.11.0" or actix = "0.12.0", other libs' version doesn't important) to cargo.toml
3. Cargo run
4. Got a compile error

## Context

I can't do anything when compiler errors occured.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.55
* Actix Version: both 0.11 and 0.12

**Comment by cv1002** [comment]
![image](https://user-images.githubusercontent.com/56287993/132956315-8241082a-ca56-4101-8c36-bb8d79f4709f.png)

**Comment by cv1002** [comment]
My English is so very good. But I really want to know why the codes don't work. I'm a new coder in rust. I found this when I'm trying to run the examples of websocket...

**Comment by cv1002** [comment]
Solved when I switched actix-web-actors into version 4.0.0-beta.7...
![image](https://user-images.githubusercontent.com/56287993/132957827-94fde40f-9e9f-4835-9a08-3a2055199dc2.png)
However my editor has a warning...

**Comment by thalesfragoso** [comment]
The latest **stable** release of `actix-web-actors` uses `actix` ^0.10, that's why they aren't compatible.

Your editor seems to be looking for the latest **stable** release, it doesn't consider beta releases, that's why you get the warning.

**Comment by cv1002** [comment]
> The latest **stable** release of `actix-web-actors` uses `actix` ^0.10, that's why they aren't compatible.
> 
> Your editor seems to be looking for the latest **stable** release, it doesn't consider beta releases, that's why you get the warning.

Thank you
