### ISSUE TITLE
Add discord link instead of gitter

### ISSUE THREAD

**Issue by LasseRosenow** [actix/actix#529]
# When you want to create a new issue, they say you should go on gitter, if you have a question.
![image](https://user-images.githubusercontent.com/10547444/159547784-8f26a012-55f6-45d8-8c6f-bb883b298f26.png)
# But the gitter link is dead.
![image](https://user-images.githubusercontent.com/10547444/159547875-cb8f1c18-fe4a-4571-8fa1-ce2287f63ab5.png)

# But there is a discord
It seems like there is an official actix discord: https://discord.gg/NWpN5mmg3x
Its called actix web, but it also has an `actors` channel which is all about asking questions on the actors framework, so why not add it instead of gitter?

**Comment by robjtede** [comment]
thx, updated
