### ISSUE TITLE
Stopping system always logs warning

### ISSUE THREAD

**Issue by rvlzzr** [actix/actix#53]
It looks like sending SystemExit to the system arbiter causes it to send StopArbiter to all arbiters including itself, and a warning is logged whenever system arbiter receives StopArbiter.

System arbiter received `StopArbiter` message.
                  To shutdown system, `SystemExit` message should be
                  send to `Addr<Syn, System>`

Can system either not send StopArbiter to itself, or not log this warning when it is the process of shutting down after receiving SystemExit?

**Comment by fafhrd91** [comment]
Good catch! I will fix this

**Comment by fafhrd91** [comment]
fixed in master.

btw would you mind tell me what do you use actix for?
