### ISSUE TITLE
Consider updating `actix-derive` to use `syn@2`

### ISSUE THREAD

**Issue by LikeLakers2** [actix/actix#552]
Hi! I noticed that `actix-derive` depends on `syn@1`. Perhaps you could consider updating it to use `syn@2`?

Some things worth noting for anyone who intends to take on this suggestion:
* `syn@2`'s MSRV is Rust 1.56, up from `syn@1`'s Rust 1.31. I am unsure how this fits with `actix-derive`, however I do note that `actix`'s MSRV is 1.57 (according to the repository README), which *probably* means this shouldn't be a problem?
* Updating to `syn@2` may not be as simple as swapping the version number - there are a number of breaking changes in `syn@2`, listed at <https://github.com/dtolnay/syn/releases/tag/2.0.0>.

If you do consider to transition to `syn@2`, you have my thanks! :)

**Comment by jeizsm** [comment]
I will try to do it

**Comment by LikeLakers2** [comment]
@robjtede Ah, sorry for saying this sort of late, but I wouldn't label this as a "good first issue". I misunderstood how many changes would need to be made, and how much of what equates to a new architecture would need to be understood - and this only occurred to me after someone pointed it out on the issue I left on the Bevy Engine repository. <https://github.com/bevyengine/bevy/issues/8282#issuecomment-1495348184>

**Comment by robjtede** [comment]
done in #554
