### ISSUE TITLE
Build fail due to "ahash v0.7.7" error[E0635]: unknown feature stdsimd

### ISSUE THREAD

**Issue by ArunGust** [actix/actix#580]
unknown feature stdsimd : Got below after updating rust to new version rustc 1.78.0-nightly (f067fd608 2024-02-05)
error[E0635]: unknown feature stdsimd
--> C:\RUST\CARGO\registry\src\index.crates.io-6f17d22bba15001f\ahash-0.7.7\src/lib.rs:33:42
|
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
| ^^^^^^^

For more information about this error, try rustc --explain E0635.
error: could not compile ahash (lib) due to 1 previous error

**Comment by robjtede** [comment]
Nightly regression in ahash. Please enquire with them.
