### ISSUE TITLE
Documentation of stream handling is unclear

### ISSUE THREAD

**Issue by uzytkownik** [actix/actix#59]
Currently the documentation states:

> This method is similar to `add_future` but works with streams.
>
> Information to consider. Actor wont receive next item from a stream until `Response` future resolves to a result. `Self::reply` resolves immediately.
>
> This method is similar to `add_stream` but it skips result error.

However there is no `add_future` method that search can find and it is unclear what `Response` future it refers to. (I'm trying to look for method of temporarily stopping the processing of stream without stopping context - it looks like what I'm looking for but I cannot figure what the documentation intends to convey).

**Comment by uzytkownik** [comment]
I think `add_feature` is meant to be `spawn`. That said I cannot figure out what it is suppose to do.

**Comment by fafhrd91** [comment]
sorry, I am a bit busy at the moment. I will fix doc in few hours

**Comment by DoumanAsh** [comment]
@fafhrd91 I can take on updating docs for `StreamHandler` since I was using it recently.
I think `add_stream` should refer to `StreamHandler` and there we can add all needed information on how it should work

**Comment by fafhrd91** [comment]
@DoumanAsh sure

**Comment by uzytkownik** [comment]
No worries.

In meantime is there a way of blocking stream I don't see? I can implement it [myself](https://gist.github.com/uzytkownik/edd622a9334058de97bd20c658738e91)  but IMHO it looks kind of awkward.

**Comment by fafhrd91** [comment]
You can just create timeout future and [wait](https://actix.github.io/actix/actix/trait.AsyncContext.html#tymethod.wait) for it. While waiting actor is paused

**Comment by uzytkownik** [comment]
@fafhrd91 I know but I don't want to pause actor - I want to pause the stream (or rather processing of stream). Given your comment I'm assuming there isn't such thing despite quoted comment suggesting otherwise.

------------------------

This gets slightly off-topic but the comment suggested there was some way I could block stream. I'm assuming it happens with [`add_message_stream`](https://actix.github.io/actix/actix/trait.AsyncContext.html#method.add_message_stream) when I return a [Future](https://actix.github.io/actix/actix/prelude/type.ResponseFuture.html) but [it doesn't seem to do so](https://github.com/actix/actix/blob/master/src/contextitems.rs#L113) (my underlying problem is that I want two websocket threads to communicate. However if I wait and they both try to send messages they will deadlock).

**Comment by DoumanAsh** [comment]
@uzytkownik You can move to gitter chat for off-topic. But note that even if you want to block only stream, you're likely to block everything else by it too unless you convert it to ActorFuture

**Comment by fafhrd91** [comment]
updated
