### ISSUE TITLE
Futures 0.3.0 support

### ISSUE THREAD

**Issue by tinrab** [actix/actix#69]
Any plans to support [futures 0.2.0](https://crates.io/crates/futures)? There were some breaking changes that don't work with actix 0.5.6.

**Comment by philblanks** [comment]
[futures 0.3 roadmap](https://github.com/rust-lang-nursery/futures-rs/milestone/2)

**Comment by krircc** [comment]
@fafhrd91 [RFC: stabilize `std::task` and `std::future::Future` ] now merged. can actix only base on The std Future and task or support it？

**Comment by Kroisse** [comment]
I made a crate to use futures 0.3 with Actix easier. Feel free to include it when the async support of Rust has stabilized.

https://crates.io/crates/actix-async-await

**Comment by najamelan** [comment]
@Kroisse version 0.3.0? ;)  Thanks

**Comment by zmlzm** [comment]
hello, The [office async runtime](https://github.com/rustasync/runtime) is out, maybe It is a good chioose

**Comment by DoumanAsh** [comment]
@zmlzm As long as `Future` is not stable, it doesn't matter.

P.s. I doubt it is official as long as it is not part of Rust's std

**Comment by zmlzm** [comment]
@DoumanAsh ye, Future will be stable at 1.36. then the runtime library will be better, you can chioose the default async runtime or the tokio runtime in it. 
Also actix-* can base on std Future to build own async runtime. Then no dependent problem forever. 
I think the futures library is for some experiment features for one day into STD,  if actix-* target production，It should be dependent on std Future, no futures library.

**Comment by tiberiusferreira** [comment]
The (not yet final) await syntax has landed on nightly as per https://github.com/rust-lang/rust/pull/60586 . Moving to the stable (in 1.36) Futures 0.3 would allow nightly users use the full async await syntax.

**Comment by semtexzv** [comment]
Since new futures with async-await syntax are almost on stable, i think it's time to revisit this issue.

**Comment by semtexzv** [comment]
I started the work on this in my fork:  [actix-net](https://github.com/semtexzv/actix-net) + [actix](https://github.com/semtexzv/actix)

**Comment by guoli-lyu** [comment]
@semtexzv I will give a try. I didn't find any documentation or etc that clearly states what need to be done and what is the current stage. Shall we make a new issue and track the progress toward future 0.3 there? Or is it too early?

**Comment by semtexzv** [comment]
Well, the first thing is to port actix-net/actix-rt, which is almost done,
Then the rest of the actix-net group.

Porting of actix is parallel to these tasks.

But yes, I think there should be issues in actix-net repo and actix repo to track progress and make decisions. Because currently, there is at least one thing, that is not clear, whether it should be changed.
