### ISSUE TITLE
multiple schedulers?

### ISSUE THREAD

**Issue by Licenser** [actix/actix#82]
Hi,
I'm looking at the different actor systems that currently exist for rust and actix seems to be the most developed from what I can tell. To get a feeling for the system(s) I started to implement the ring benchmark and compare them to Erlang as a baseline [1].

I noticed that actix by default only uses a single core/scheduler and was wondering what the most straightforward way to spread out work over all the available cores. I've looked around and the only thing I could find so far is "run an actor on a different thread" but that seems like it has to be hard-coded on a per actor level. 

Cheers,
and many thanks in advance!

[1] https://github.com/Licenser/rust_ring

**Comment by fafhrd91** [comment]
Actix does not provide any automatic scheduling. It is lower level than erlang. Developer is responsible joe actor get executed

**Comment by fafhrd91** [comment]
There is ring bench in #52

**Comment by Licenser** [comment]
Thanks for the quick reply :) I'm glad I didn't miss anything and I'll take a peak at the benchmark in #52 that looks quite interesting and probably something to learn from :D. I guess learning how to schedule my own actors will be a good way of understanding how actix works :) many thanks for the great work!

**Comment by fafhrd91** [comment]
you are welcome
