### ISSUE TITLE
How to use an AsyncWriter with an actor?

### ISSUE THREAD

**Issue by alanhoff** [actix/actix#84]
Hello folks, I have a `WriteHalf<TcpStream>` but I'm not sure how to attach it to an `Actor`. I wrote a [small prototype](https://gist.github.com/alanhoff/ed8f38afb3d80e0fa757eca339bdcd77) with an actor that reads from a `ReadHalf<TcpStream>` and writes to a `WriteHalf<TcpStream>`, basically an echo server. The problem is that it's not writing/flushing immediately:

<img width="198" alt="screen shot 2018-05-22 at 15 11 41" src="https://user-images.githubusercontent.com/1044223/40381666-b6eb1dbc-5dd2-11e8-8033-faca10bb09ac.png">

The desired output would be:

```
> hello\r\n
< hello\r\n
> world\r\n
< world\r\n
```

But the server is echoing the first line only when I send a second one.

Thanks!

**Comment by fafhrd91** [comment]
you can set buffer size to 0, http://actix.rs/actix/actix/io/struct.FramedWrite.html#method.set_buffer_capacity

i am planing to revisit this api. write part is not in good shape.

**Comment by alanhoff** [comment]
I'll reopen bc I think this might be a bug. Even using `set_buffer_capacity` didn't worked. Could it be related to the to the tokio version I'm using (0.1.6)? My example is here:

* https://github.com/alanhoff/rust-example-actix

**Comment by fafhrd91** [comment]
version of tokio should not matter, I will check

**Comment by alanhoff** [comment]
I made some kind of progress: it seems like using [`set_send_buffer_size(1)`](https://docs.rs/tokio/0.1.6/tokio/net/struct.TcpStream.html#method.set_send_buffer_size) kinda helps, when using socat the first command still buffers but the rest is sent immediately.

```
> hello\r\n
> world\r\n
< hello\r\n
< world\r\n
> hello\r\n
< hello\r\n
> world\r\n
< world\r\n
```

**Comment by fafhrd91** [comment]
sorry, I am busy at the moment. I'll check this bug over weekend

**Comment by alanhoff** [comment]
So it turns out it wasn't a bug, my `Stream` implementation was wrong. I pushed a working version to the same repository. Thx for the patience!

**Comment by habnabit** [comment]
For what it's worth, #97 might be related.
