### ISSUE TITLE
how could i auto run each actor in different thread?

### ISSUE THREAD

**Issue by woodgear** [actix/actix#88]
wrap actor.start() in thread? is there same config about that?

**Comment by DoumanAsh** [comment]
For such questions I'd suggest to visit [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

But to answer actix itself is based on tokio so in general actors will schedule futures on this only thread.
But you can still use things like [Arbiter](https://docs.rs/actix/0.5.7/actix/struct.Arbiter.html) or [SyncArbiter](https://docs.rs/actix/0.5.7/actix/sync/struct.SyncArbiter.html) to run your actors in own thread or thread pool
