### ISSUE TITLE
Passing Actor Address to Separate Service

### ISSUE THREAD

**Issue by nevi-me** [actix/actix#89]
Hi,

I have an actor whose address I got when starting it:

```rust
let addr: Addr<Unsync, _> = Actor(
    ...
).start();
```

I am trying to pass the address to a different service that receives messages via gRPC.

The service can accept data/references through a struct:

```rust
struct MyServiceImpl {
    address: Addr<Unsync, _>
}
```

Firstly, should I be passing the actor's address around? If so, what should I replace the `_` with on `MyServiceImpl`?

I've been going through the documentation trying to figure out what to replace the `_` with on `MyServiceImpl`, as I can't use the type placeholder.

Thanks.

**Comment by DoumanAsh** [comment]
I would suggest to go over our [gitter](https://gitter.im/actix/actix) for such talks

If you take a look at Address, it can be cloned easily which means it is safe to pass it around. It more or less acts as a way to address your actor.
Note that it also implements `Send` and `Sync` so you can send it even across threads

I guess it may not be clear from `Actor::start()` signature
The second type parameter in Addr is Actor type

Hope it answers your questions. If you have more feel free to jump into gitter

**Comment by nevi-me** [comment]
Thanks, I missed the Gitter channel. Will head there.

I'll play around with what you've said, and if I have questions I'll ask on Gitter.
