### ISSUE TITLE
Define concurrency model and terms

### ISSUE THREAD

**Issue by mitchtbaum** [actix/actix#9]
While studying [Kabuki](https://github.com/carllerche/kabuki) and [Akka](https://github.com/akka/akka) recently, I read mostly about their [Actor model](https://en.wikipedia.org/wiki/Actor_model) and its terms, but this [list of concurrency models](https://stackoverflow.com/questions/4153118/list-of-concurrency-models) shows that it is only one family, among even [Process Algebra](https://en.wikipedia.org/wiki/Process_calculus), "a diverse family of related approaches for formally modelling concurrent systems".  Many of them have non-descriptive names, so perhaps it would make the most sense to simply list which possible features of various [Models for Programming Concurrency](http://berb.github.io/diploma-thesis/original/023_concurrency.html#models) this project aims to implement.

Also, based on [noxisacat's reply to Actix 0.1 release announcement](https://www.reddit.com/r/rust/comments/75u7qu/actix_01_released_actor_framework_for_rust/do9d3j0/) advising to switch away from Actor Model terms, since this project differs from its model, I picked out (possibly more) general and familiar concurrency terms, oriented toward teamwork and logistics, for a starting point in this:

[`Actor`](https://fafhrd91.github.io/actix/actix/trait.Actor.html) ~> `Delegate`: takes a job for processing

`Item` ~> `Job`: piece of work

`Cell` ~> `Schedule`: ordering of a set of jobs

[`Supervisor`](https://fafhrd91.github.io/actix/actix/struct.Supervisor.html) ~> `Dealer`: sends jobs to delegates' schedules

[`Arbiter`](https://fafhrd91.github.io/actix/actix/struct.Arbiter.html) ~> `Broker`: sets how to use a field and which processes take place in it

[`System`](https://fafhrd91.github.io/actix/actix/struct.System.html) ~> `Field`: an environment for performing activities 

[`Context`](https://fafhrd91.github.io/actix/actix/struct.Context.html) ~> `Track`: a laid out, measurable path with activities to follow; eg. [on track](https://en.wiktionary.org/wiki/on_track) and [fast track](https://en.wiktionary.org/wiki/fast_track)

[`State`](https://fafhrd91.github.io/actix/actix/enum.ActorState.html) ~> `Progress`: measure of movement towards or away from defined start and end points; eg. [work-in-progress](https://en.wiktionary.org/wiki/work-in-progress) and [progress report](https://www.merriam-webster.com/dictionary/progress%20report)

**Comment by fafhrd91** [comment]
does it matter at all? I am not sure if this makes sense. also some of terms are not really describes actix functionality. Actor is not worker, system is not field, context is not track. etc

**Comment by fafhrd91** [comment]
another question. why is it so important to have different terms?

**Comment by mitchtbaum** [comment]
With (and even without) [model-driven engineering](https://en.wikipedia.org/wiki/Model-driven_engineering), using easily understandable terms makes the area of development, [domain model](https://en.wikipedia.org/wiki/Domain_model), most accessible.  Otherwise people get caught up trying to adapt to a foreign language or a jargon which they have no pre-existing familiarity.  Since many people have backgrounds outside of CS (like myself), I've found that explaining things in relateable terms bridges gaps nearly instantaneously and dissolves fear of complexity; and I find this only after I have to work very hard to understand these things myself.

Just taking Actor for example, one would initially imagine this framework has something inside of it related to theater (hence the Kabuki project name).  Since I found that Akka explains it as ~"Supervisor delegating a Task", I thought "oh, that fits a whole lot better".  So, my first name change, at least in my own mind, was Actor ~> Delegate (though I put worker); and that's how I intended to explain it to others in the future.  Since many people have background experiences in teamwork settings using delegate-related terms, it can work well as an understanding framework.  If you also see Delegation as a relateable mental model for concurrent programming or any other better one with simple, straightforward terms, then users and developers can benefit from the get go.

**Comment by mitchtbaum** [comment]
I agree that switching Actor with Worker, and now especially Context with Track, were bad choices; but I hope that Item and Cell for Job and Schedule were at least somewhat of a hit.  They might still need some improvement though, for sure.

**Comment by fafhrd91** [comment]
I am happy to change naming. But actix does not use term Job or Schedule at all.
here are basic terms actix uses: Actor, Address, Context. thats it, everything else just helper terms

**Comment by fafhrd91** [comment]
@mitchtbaum is there any actionable in this issue?

**Comment by mitchtbaum** [comment]
If you're up for analyzing a couple of different models and terminologies, I could use that to refine, not the functionality of the software, rather how it is represented.

This research brief summarizes the key concepts involved, [Mental models: helping users understand software](https://sci-hub.cc/http://ieeexplore.ieee.org/document/35592).

**Comment by mitchtbaum** [comment]
The fundamental target here is for anyone who wants to understand this project to start by reading a short summary of its features to get a big picture view in their mind, like that figure 1b (even better if it fits in some grouping among other documented concurrency models).  And then any terms they pickup from that point would align with closer study of the internals.

**Comment by fafhrd91** [comment]
I understand reasons for better terms. This set of terms is what I came up with, could you provide better terms?

**Comment by fafhrd91** [comment]
I am fine with changing terms, I just can not find better

**Comment by mitchtbaum** [comment]
[Chymyst](https://github.com/Chymyst/chymyst-core) uses chemistry terms in its implementation, ie molecules and reactions.  It looks well-documented, relevant, and advanced enough to mention here for your consideration.

**Comment by fafhrd91** [comment]
I am not sure how any of the terms you provided actually related to actix. lets restate, I am not sure that any of those terms can make actix terms any clearer

**Comment by superlou** [comment]
Having spent a few hours with Actix, I don't think the names are a source of confusion.  Every framework has a habit of bringing some terms of art, and Actix's seem pretty tame.  Maybe more use case examples would be enough to show the meaning behind the current naming?

**Comment by mitchtbaum** [comment]
Even the terms Actor and Process Calculus are unclear.  I'm watching the [Chymyst video](https://www.youtube.com/watch?v=jawyHGjUfBU) now, and he just said that it can run either on top of thread pools or Akka actors.  So it appears that the Actor model (and potentially other concurrency models) are a more low-level feature set of the same functionality as Process Calculus, and then with a higher-level language on top of it, the features planned in other related models apply.

So, even before providing terms, I'm trying to get a frame of reference what happens in Actix and similar software in order to group it among similar software and possibly relate it to something more familiar, like chemical reactions, team planning and working, or another concurrent concept.  What you said earlier about Actor, Address, and Context making up the core functionality and other pieces of functionality acting as helpers gave a clearer sense about the architecture.  I'll keep looking for what else I can add for now.

**Comment by fafhrd91** [comment]
I definitely have plans for more examples, but I am busy with actix-web at the moment.

@superlou btw would you share your thoughts on actix?

**Comment by superlou** [comment]
@fafhrd91 I'm probably not a great resource with respect to Rusty patterns, as I'm using my current project as a way to learn Rust.  I'm using the `irc` crate to make a set of IRC bots that communicate with users in an interactive game.  I started using Actix since there is a lot of game state that needs to be shared between the bots.  I am trying to convert my existing spaghetti code to instead put the game logic into an `Engine` actor which can start `Bot` actors as it needs.  The bots are then just shells that send messages to the engine, which evaluates the user interaction and sends back what the bot should print.  For this simple case, the naming of Actors, Handlers, and Systems seemed sensible.

This might be a silly thing, but I did notice that it does seem to be difficult to use descriptive signal names because the length of the `handle` definition gets very long:

```
impl Handler<ConnectToServer> for Bot {
    fn handle(&mut self, msg: ConnectToServer, ctx: &mut Context<Self>) -> Response<Self, ConnectToServer> {
    ...
```

My current hang-ups are that since the IRC message handling is blocking, I need to pass an address from the engine into a thread that the bots spawn.  I believe this is done by upgrading an `Address` to a `SyncAddress`, but I'm stuck learning how to handle the future returned by `upgrade()`.

**Comment by mitchtbaum** [comment]
> Every framework has a habit of bringing some terms of art, and Actix's seem pretty tame. 

@superlou Thank you for saying this.  DX is my primary motive and linguistic patterns second.

**Comment by fafhrd91** [comment]
@superlou this is very valuable! 

regarding address, you can get SyncAddress during creation of an actor, like:
```
let addr: SyncAddress<_> = Bot::start()
```

regarding waiting for some future, example with upgrade: 
```
  fn handle(&mut self, msg: M, ctx: &mut Context) -> Response<..> {
      self.addr.upgrade().then(|addr, slf, ctx| {
         // do something
      }).wait(ctx);
  }
``` 
`slf` would be mutable reference to `self`

**Comment by superlou** [comment]
@fafhrd91 The first option (telling it to give me a SyncAddress<_>) worked.  The generic is pretty clever, but I'm not sure I would've found that from [the api](https://docs.rs/actix/0.2.0/actix/trait.Actor.html#method.start).  I guess something like `.start_sync` would be confusing since it's still an asynchronous actor?  If there were explicit functions, would you not need to define the variable type, e.g. `let my_actor = MyActor.start()`?

**Comment by fafhrd91** [comment]
@superlou 
you have to use `Arbiter`, Arbiter controls event loop. then you can send `StartActor` message to `Arbiter`. 
```rust

fn handle(&mut self, msg: M, ctx: &mut Context) -> Response<..> {
      let arbiter = Arbiter::new("bot");
      arbiter.call(self, msgs::StartActor::new(|ctx| Bot{})).then(|addr, slf, ctx| {
         // do something
      }).wait(ctx);

      Self::empty()
  }
```

definitely, this needs to be simpler. There is no big difference when to create address, so `StartActor` message actually can create address before sending to arbiter

**Comment by fafhrd91** [comment]
@mitchtbaum at the moment I can not find any better terms that I already use. if you think you have better idea, please reopen

**Comment by naturallymitchell** [comment]
Here are some research materials that really help understand threading in sewing and work in delegating.

[Tutorial: how to use the BERNINA multiple spool holder](https://www.youtube.com/watch?v=FeE3YB7gzIw)

[Introduction to HAPPY's HCR3 Multihead Embroidery Machine Line](https://www.youtube.com/watch?v=O_Mfu1ZxQ4o)

https://github.com/actix/actix/issues/19
