### ISSUE TITLE
README.md User Guide hyperlink http://actix.github.io/actix/guide/ returns 404

### ISSUE THREAD

**Issue by ykoehler** [actix/actix#92]
I am trying to access the user guide but I am getting a 404 error.

**Comment by DoumanAsh** [comment]
@fafhrd91 @mitsuhiko Do you know where went user guide for actix themself with introduction of new site?

I remember we had separate user guide for `actix` and `actix-web`

**Comment by mitsuhiko** [comment]
It’s intentionally not there at the moment. It’s just in a repo somewhere
in the actix github org in markdown files.

**Comment by fafhrd91** [comment]
guide link is fixed

**Comment by fafhrd91** [comment]
https://actix.rs/book/actix/

**Comment by deontologician** [comment]
It's fixed, but the examples are wrong as of 0.6, they refer to
Arbiter::handle()

**Comment by fafhrd91** [comment]
Examples need some time
